navikt/su-se-framover

.vscode/tasks.json
package-lock.json
package.json
src/Root.tsx
src/components/FormElements.tsx
src/features/søknad/søknadSlice.ts
src/lib/hooks.ts
src/lib/validering.ts
src/pages/søknad/bunnknapper/Bunnknapper.tsx
src/pages/søknad/index.tsx
src/pages/søknad/steg-shared.module.less
src/pages/søknad/steg/bo-og-opphold-i-norge/Bo-og-opphold-i-norge.tsx
src/pages/søknad/steg/flyktningstatus-oppholdstillatelse/Flyktningstatus-oppholdstillatelse.tsx
src/pages/søknad/steg/formue/DinFormue.tsx
src/pages/søknad/steg/inngang/Inngang.tsx
src/pages/søknad/steg/inngang/inngang.module.less
src/pages/søknad/steg/inntekt/Inntekt.tsx
src/pages/søknad/steg/kontakt/Kontakt.tsx
src/pages/søknad/steg/oppsummering/Oppsumering.tsx
src/pages/søknad/steg/steg-shared-i18n.ts
src/pages/søknad/steg/uførevedtak/Uførevedtak.tsx
src/pages/søknad/steg/utenlandsopphold/Utenlandsopphold.tsx
src/pages/søknad/steg/utenlandsopphold/utenlandsopphold-nb.ts
src/pages/søknad/steg/utenlandsopphold/utenlandsopphold.module.less
tsconfig.json

Dette ble gjort i samarbeid med @RamziAbuQassim .

Søknad: legg til validering

---

src/features/person/person.slice.ts
src/pages/søknad/bunnknapper/Bunnknapper.tsx
src/pages/søknad/bunnknapper/bunnknapper.module.less
src/pages/søknad/index.tsx
src/pages/søknad/steg/inngang/Inngang.tsx
src/pages/søknad/steg/inngang/inngang-nb.ts
src/pages/søknad/steg/inngang/inngang.module.less

- Flyten og visningen for å søke etter person for deretter å starte søknad er nå tydeligere
- For bunnknappene vil tabbing til dem gå til "Neste"-knappen før til "Forrige"-knappen

Søknad: forbedre inngangssiden og bunnknappene

---

src/lib/validering.ts
src/pages/søknad/steg/utenlandsopphold/Utenlandsopphold.tsx

- Fiks knytning mellom feiloppsummeringen og de faktiske feltene
- Forbedre styling på input-ene

Utenlandsopphold: forbedre validering

---

src/pages/søknad/index.tsx

Fikset stegindikatoren sammen med Aryan

Fiks stegindikatoren

---

src/Root.tsx
src/api/apiClient.ts
src/api/behandlingApi.ts
src/api/personApi.ts
src/api/sakApi.ts
src/api/søknadApi.ts
src/features/saksoversikt/sak.slice.ts
src/features/søknad/innsending.slice.ts
src/pages/saksoversikt/Saksoversikt.tsx
src/pages/saksoversikt/sakintro/Sakintro.tsx
src/pages/saksoversikt/vilkår/Vilkår.tsx
src/pages/saksoversikt/vilkårsvurdering/Vilkårsvurdering.tsx

- validering på skjema i vilkårsvurdering
- lagring av vilkårsvurderinger

Oppdater struktur til å reflektere ny domenestruktur fra backend

---

src/Root.tsx
src/lib/routes.ts

it makes more sense now when we have a 'log out' feature to redirect a user to a login page, instead of directly redirecting them to the external login link.

Go to login page instead of redirecting user to nav login

---

src/api/behandlingApi.ts
src/features/saksoversikt/utils.tsx
src/pages/saksoversikt/Saksoversikt.tsx
src/pages/saksoversikt/beregning/Beregning.tsx
src/pages/saksoversikt/beregning/beregning-nb.ts
src/pages/saksoversikt/beregning/beregning.module.less
src/pages/saksoversikt/types.ts
src/pages/saksoversikt/vedtak/Vedtak.tsx
src/pages/saksoversikt/vedtak/vedtak.module.less
src/pages/saksoversikt/vilkår/Vilkår.tsx
src/pages/saksoversikt/vilkårsvurdering/Vilkårsvurdering.tsx

Co-authored-by: Ingar Almklov <ingara@gmail.com>
Co-authored-by: John Andre Hestad <john.hestad.andre@nav.no>

legg til beslutningsgrunnlag/behandlingsresultat side

---

src/components/FormElements.tsx
src/components/formElements.module.less
src/lib/tracking/trackingEvents.ts
src/lib/tracking/trackingTypes.ts
src/pages/søknad/steg/oppsummering/Oppsummering.tsx
src/pages/søknad/steg/oppsummering/Søknadoppsummering/Søknadoppsummering.tsx

Lagt till tracking før:
- Klikk på hjelpetekst
- Send inn søknad

Tracking søknad

---

src/api/søknadApi.ts
src/features/søknad/innsending.slice.ts

Fix for frontend för att matcha backenden igen. 
Nå skal det gå att sende in søknader!

Send bare fødselsnummer som personalia

---

src/Root.tsx
src/api/behandlingApi.ts
src/features/saksoversikt/sak.slice.ts
src/lib/routes.ts
src/pages/HomePage/index.tsx
src/pages/attestering/Attestering.tsx
src/pages/attestering/Attesteringsliste.tsx
src/pages/attestering/AttesteringslisteElement.tsx
src/pages/attestering/Attesteringsoversikt.tsx
src/pages/attestering/attestering-nb.ts
src/pages/attestering/attestering.module.less
src/pages/saksoversikt/Saksoversikt.tsx
src/pages/saksoversikt/søkefelt/Søkefelt.tsx

Lagt upp grundläggande struktur för sidan kring attestering.

Attestering

---

src/api/behandlingApi.ts
src/pages/saksoversikt/beregning/VisBeregning.tsx
src/pages/saksoversikt/beregning/visBeregning.module.less
src/pages/saksoversikt/delt/Infolinje/Infolinje.tsx
src/pages/saksoversikt/delt/Infolinje/infolinje.module.less
src/pages/saksoversikt/simulering/simulering.tsx
src/pages/saksoversikt/vedtak/Vedtak.tsx

Avhenger av https://github.com/navikt/su-se-framover/pull/204 for å fungere som tiltenkt. Null skills på frontend og måtte kjøre noe --no-verify for å få pusha, sikkert lurt om noen låner denne et øye.
Gamle simuleringer som feiler kan løses med å simulere på nytt.

simple display of simulering

---

.vscode/tasks.json
src/components/FormElements.tsx
src/pages/saksoversikt/vilkår/Faktablokk.tsx
src/pages/saksoversikt/vilkår/Sats.tsx
src/pages/saksoversikt/vilkår/VilkårV2.tsx
src/pages/saksoversikt/vilkår/faktablokk.module.less
src/types/Behandlingsinformasjon.ts

Also:
- VSCode Task: stop the problems window from taking focus all the time
- FormElements: add SuperRadio and SuperRadioGruppe

Saksbehandling: add page for Sats

---

src/pages/saksoversikt/vedtak/Vedtak.tsx
src/pages/saksoversikt/vilkår/VilkårV2.tsx

Fix routing for when `status === VILKÅRSVURDERT_AVSLAG`.

Fix routing for status avslag

---

src/api/behandlingApi.ts
src/features/behandling/behandlingUtils.ts
src/pages/attestering/Attestering.tsx
src/pages/saksbehandling/sakintro/Sakintro.tsx
src/pages/saksbehandling/vedtak/Vedtak.tsx

Also moved utils for behandling into its own folder

Fix feedback for sending in attestering

---

src/api/behandlingApi.ts
src/components/Hendelseslogg.tsx
src/components/hendelseslogg.module.less
src/features/behandling/behandlingUtils.ts
src/features/saksoversikt/sak.slice.ts
src/pages/attestering/Attestering.tsx
src/pages/saksbehandling/Saksoversikt.tsx
src/pages/saksbehandling/steg/formue/Formue.tsx
src/styles/variables.less
src/types/Behandling.ts

Lagt till en händelseslogg i saksöversikten.
Just nu stöttes bara ett event och det är 'underkjent' för attestering.

Hendelseslogg

---

src/Root.tsx
src/api/meApi.ts
src/features/me/me.slice.ts
src/lib/cookies.ts
src/redux/Store.ts
src/types/LoggedInUser.ts

Also check auth status by fetching info about logged-in user
Depends on https://github.com/navikt/su-se-bakover/pull/52

 Add MeSlice: holds information about the logged-in user

---

src/pages/saksbehandling/steg/formue/Formue.tsx
src/pages/saksbehandling/steg/uførhet/Uførhet.tsx

Bug: Vi hade olika save-logik på lagringsknapparna. 👻
Nå bruker en och samma `onSave`-funktion för att förhindra det. 😸

Fix inconsistencies with saving behandlingsinformasjon

---

src/pages/saksbehandling/steg/flyktning/Flyktning.tsx
src/pages/saksbehandling/steg/lovlig-opphold-i-norge/LovligOppholdINorge.tsx
src/pages/saksbehandling/steg/personlig-oppmøte/PersonligOppmøte.tsx
src/pages/saksbehandling/steg/uførhet/Uførhet.tsx

Skal ikke preutfylle saksbehandlingen basert på ting från søknaden.

Remove default values from søknad

---

src/Root.tsx
src/context/userContext.tsx
src/lib/cookies.ts
src/pages/HomePage/index.tsx
src/pages/saksbehandling/sakintro/Sakintro.tsx

Den siste endringen her avhenger av https://github.com/navikt/su-se-bakover/pull/65

UserContext: keep value from GET /me, check for NAVIdent when showing Attester button

---

src/Root.tsx

Avhenger av https://github.com/navikt/su-se-bakover/pull/77

Improve logout functionality

---

src/pages/saksbehandling/steg/beregning/Beregning.tsx
src/pages/saksbehandling/steg/beregning/DelerAvPeriodeInputs.tsx
src/pages/saksbehandling/steg/beregning/FradragInputs.tsx
src/pages/saksbehandling/steg/beregning/VisBeregning.tsx
src/types/Fradrag.ts

Fix issues with fradrag regarding:
* Referencing wrong field names (`delerAvPeriode` -> `inntektDelerAvPeriode`).
* Data having duplicated entries of "ForventetInntekt"-fradrag.

Fix issues with fradrag in beregning

---

src/api/søknadApi.ts
src/features/saksoversikt/sak.slice.ts
src/features/søknad/søknad.slice.ts
src/lib/routes.ts
src/pages/saksbehandling/Saksoversikt.tsx
src/pages/saksbehandling/sakintro/AvsluttBehandling.tsx
src/pages/saksbehandling/sakintro/Sakintro.tsx
src/types/Søknad.ts

gamle pr: https://github.com/navikt/su-se-framover/pull/297
skal forhåpentligvis være mer solid.

Trekk søknad

---

src/pages/saksbehandling/steg/beregning/FradragInputs.tsx
src/pages/saksbehandling/steg/beregning/VisBeregning.tsx
src/pages/saksbehandling/steg/beregning/beregning-nb.ts
src/pages/saksbehandling/steg/beregning/beregningUtils.ts
src/types/Fradrag.ts

Fikset også slik at riktige tekster for fradragstypene vises i beregningsvisningen.

Update list of fradragstyper

---

src/index.js
src/indexUtils.ts
src/pages/saksbehandling/Saksoversikt.tsx
src/pages/saksbehandling/sakintro/Sakintro.tsx
src/pages/saksbehandling/sakintro/Utbetalinger.tsx
src/pages/saksbehandling/sakintro/sakintro-nb.ts
src/pages/saksbehandling/sakintro/sakintro.module.less
src/pages/saksbehandling/sakintro/utbetalinger-nb.ts
src/pages/saksbehandling/sakintro/utbetalinger.module.less

Split åpne and avslåtte søknader. Utbetalinger freshed up

New look for Saksoversikt

---

.github/workflows/branch.yml
.github/workflows/master.yml
src/pages/saksbehandling/sakintro/Utbetalinger.tsx

Ninja merge ettersom small-fix har blitt testet i miljøet OK

Saksoversikt fix

---

src/features/søknad/innsending.slice.ts
src/features/søknad/søknad.slice.ts
src/features/søknad/types.ts
src/pages/saksbehandling/steg/personlig-oppmøte/PersonligOppmøte.tsx
src/pages/saksbehandling/steg/personlig-oppmøte/personligOppmøte-nb.ts
src/pages/søknad/index.tsx
src/pages/søknad/nb.ts
src/pages/søknad/steg/for-veileder/ForVeileder.tsx
src/pages/søknad/steg/informasjon-om-papirsøknad/InformasjonOmPapirsøknad.tsx
src/pages/søknad/steg/informasjon-om-papirsøknad/informasjonOmPapirsøknad-nb.ts
src/pages/søknad/steg/informasjon-om-papirsøknad/informasjonOmPapirsøknad.module.less
src/pages/søknad/steg/inngang/Inngang.tsx
src/pages/søknad/steg/kvittering/Kvittering.tsx
src/pages/søknad/types.ts
src/types/Søknad.ts

Avhenger av https://github.com/navikt/su-se-bakover/pull/111

Add support for submitting papirsøknad

---

src/api/pdfApi.ts
src/api/søknadApi.ts
src/features/saksoversikt/sak.slice.ts
src/features/søknad/innsending.slice.ts
src/pages/attestering/Attestering.tsx
src/pages/søknad/steg/kvittering/Kvittering.tsx

Støtter visning/utskrift av søknaden på kvitteringssiden.

Søknadsutskrift

---

src/components/VilkårvurderingStatusIcon.tsx
src/features/saksoversikt/utils.tsx
src/pages/attestering/Attestering.tsx
src/pages/saksbehandling/steg/Framdriftsindikator.tsx
src/pages/saksbehandling/vedtak/Vedtak.tsx
src/types/Vilkårsvurdering.ts

Bolding text on the currenct active vilkår

displaying icon when vilkår has been processed

---

src/api/behandlingApi.ts
src/features/saksoversikt/sak.slice.ts
src/pages/saksbehandling/steg/beregning/Beregning.tsx
src/pages/saksbehandling/steg/beregning/beregning-nb.ts
src/pages/saksbehandling/steg/beregning/beregning.module.less
src/types/Beregning.ts

Fjernet visning av sats for dagens dato og røsket opp alt tilhørende.

Remove display of sats and forventet inntekt from top of beregning page

---

src/pages/saksbehandling/steg/formue/Formue.tsx
src/pages/saksbehandling/steg/formue/formue-nb.ts

Väldigt snabb fix från en tilbakemelding från visningsmöte.
Gjort nu så att man kan se ektefelles formue från søknaden, så det blir enklare att fylla in verdierna for ektefelle.

Temporary solution for showing ektefelles formue fra søknad

---

src/api/behandlingApi.ts
src/features/saksoversikt/sak.slice.ts
src/pages/attestering/Attestering.tsx
src/pages/attestering/attestering-nb.ts
src/pages/saksbehandling/sakintro/Sakintro.tsx
src/pages/saksbehandling/sakintro/sakintro-nb.ts
src/pages/saksbehandling/sakintro/sakintro.module.less
src/types/Behandling.ts

Lagd till ny view som viser extra information när en attestant skickar tillbaka saksbehandlingen. Detta är så att saksbehandlaren skal veta varfør den blev skickad tillbaka. :)

Attestering underkjennelsesgrunn

---

src/lib/validering.test.ts
src/lib/validering.ts
src/pages/saksbehandling/steg/beregning/Beregning.tsx
src/pages/saksbehandling/steg/beregning/FradragInputs.tsx
src/pages/saksbehandling/steg/beregning/InntektFraUtland.tsx
src/pages/saksbehandling/steg/beregning/beregningstegTypes.ts
src/pages/saksbehandling/steg/beregning/fradragInputs.module.less

La også til feiloppsummering, da det manglet sårt. Oppdaget da jeg gjorde det at den konverteringen vår mellom formik-feil og det feiloppsummeringen ønsker ikke oppførte seg noe særlig på nøstede objekter. Forhåpentligvis har ikke fiksingen min av det brukket noen andre plasser.

Beregning: set beløp in NOK based on utenlandsk beløp

---

src/pages/søknad/index.module.less
src/pages/søknad/index.tsx
src/pages/søknad/steg/kvittering/Kvittering.tsx
src/pages/søknad/steg/kvittering/kvittering-nb.ts
src/pages/søknad/steg/kvittering/kvittering.module.less

And add instructions for the veileder

Clean up the kvittering page

---

package-lock.json
package.json
src/pages/saksbehandling/Saksoversikt.tsx
src/pages/saksbehandling/steg/formue/Formue.tsx
src/pages/saksbehandling/steg/formue/formue-nb.ts
src/pages/saksbehandling/steg/formue/formue.module.less
src/pages/saksbehandling/steg/types.ts
src/pages/saksbehandling/steg/vilkår/Vilkår.tsx

Avhenger av https://github.com/navikt/su-se-bakover/pull/161

Handle EPS with skjerming in behandling 

---

src/pages/saksbehandling/steg/beregning/beregning-nb.ts

This reverts commit 4dde0988d07a5e052eb408172f2fbfd0d3f5e1cc, reversing
changes made to 0cd1702f66be0dab3f0f3d2f4c602a0d09c8fdd1.

Revert "Merge pull request #468 from navikt/beløp_pr_mnd"

---

src/lib/formatUtils.test.ts
src/lib/formatUtils.ts
src/pages/saksbehandling/steg/faktablokk/faktablokker/FastOppholdFaktablokk.tsx

Lagd in formatteringsfunktion för adresser som ser till att vi får adresser på riktigt format.
Har också lagt till tester så att den fungerar som förväntat.

Adresser tests

---

src/pages/saksbehandling/steg/beregningOgSimulering/beregning/FradragInputs.tsx
src/pages/saksbehandling/steg/beregningOgSimulering/beregning/VisBeregning.tsx
src/pages/saksbehandling/steg/beregningOgSimulering/beregning/beregning-nb.ts
src/pages/saksbehandling/steg/beregningOgSimulering/beregning/visBeregning.module.less

Rounding beløp for foreign income input, replace år with month in text, add minus sign in front of eps totaltfradrag, add beløp and kurs to foreign fradrag

Add visual details for beregning

---

src/pages/saksbehandling/steg/formue/Formue.tsx
src/pages/saksbehandling/steg/formue/formue-nb.ts
src/pages/saksbehandling/steg/formue/utils.ts
src/types/Behandlingsinformasjon.ts

avhengig av: https://github.com/navikt/su-se-bakover/pull/171

Add support for adding verdi to eiendom in formue

---

src/features/behandling/behandlingUtils.ts
src/pages/saksbehandling/sakintro/Sakintro.tsx
src/pages/saksbehandling/sakintro/Utbetalinger.tsx
src/pages/saksbehandling/sakintro/sakintro-nb.ts
src/pages/saksbehandling/sakintro/utbetalinger.module.less
src/pages/saksbehandling/vedtak/Behandlingsoppsummering.tsx
src/pages/søknad/steg/bo-og-opphold-i-norge/Bo-og-opphold-i-norge.tsx
src/pages/søknad/steg/utenlandsopphold/Utenlandsopphold.tsx

Fixed date validation in søknad. Styling. Spinner shown on right button for stansUtbetalinger

Avslåtte søknader appear in Sakintro.

---

src/pages/saksbehandling/sakintro/Sakintro.tsx
src/pages/saksbehandling/sakintro/sakintro.module.less

Show only error message on the corresponding behandling in sakintro

---

src/pages/saksbehandling/steg/faktablokk/faktablokker/PersonligOppmøteFaktablokk.tsx
src/pages/saksbehandling/steg/faktablokk/faktablokker/faktablokker-nb.ts

Vi gjør denne typisk i en format-funksjon. Det er litt forskjellige ting som må gjøres hvis man skal bruke en funksjon. er kanskje ikke den smoothe måten å kode den på denne måten, men er enklest.

formatting grunnForPapirinnsending

---

src/pages/saksbehandling/Saksoversikt.tsx
src/pages/saksbehandling/behandlingsoppsummering/behandlingsoppsummering.tsx
src/pages/saksbehandling/saksoversikt-nb.ts
src/pages/saksbehandling/saksoversikt.module.less

Lade till beregning & simuleringsoppsummering i oppsumerings-vy:n.

Show beregning & simulering in oppsummering

---

src/pages/saksbehandling/steg/flyktning/Flyktning.tsx
src/pages/saksbehandling/steg/personlig-oppmøte/PersonligOppmøte.tsx

Midlertidig fix for gå til vedtak knapp når behandling er sendt tilbake fra attestering.

goToVedtak should navigate to vedtak when coming from attestant

---

nais.yml

Dette er forberedende arbeid for å flytte autentiseringen hit.

Registrer oss som en AAD-applikasjon

---

server/auth/index.ts
server/config.ts
src/Root.tsx
src/api/apiClient.ts
src/components/header/Header.tsx
src/lib/cookies.ts

Denne avhenger av https://github.com/navikt/su-se-bakover/pull/201.
Det er to ting som gjenstår etter dette: bruke Redis for caching av sessions og å sjekke hvordan refresh-tokens oppfører seg.

Gjør autentisering her, proxy alle API-kall mot su-se-bakover

---

server/proxy.ts
src/Root.tsx
src/api/featureToggleApi.ts
src/lib/featureToggles.ts
src/lib/featureToggles.tsx
src/pages/saksbehandling/Saksoversikt.tsx

Avhenger av https://github.com/navikt/su-se-bakover/pull/205

Unleash feature toggles

---

.eslintrc.js
package-lock.json
package.json
src/components/Personsøk/Personsøk.tsx
src/pages/saksbehandling/steg/personlig-oppmøte/PersonligOppmøte.tsx
src/pages/søknad/steg/flyktningstatus-oppholdstillatelse/Flyktningstatus-oppholdstillatelse.tsx
src/pages/søknad/steg/formue/DinFormue.tsx
src/pages/søknad/steg/inntekt/Inntekt.tsx

Bruker eslint-plugin-jsx-a11y til dette.

Legg til linting av vanlige UU-feil

---

.env.azure.template
.env.template
.github/release-drafter.yml
nais-dev.json
nais-prod.json
package-lock.json
server/config.ts

Forklar bedre hva én miljøvariabel representerer og fjern én vi ikke trenger.

Rydd litt i miljøvariablene

---

src/pages/saksbehandling/steg/faktablokk/faktablokker/SatsFaktablokk.tsx
src/pages/saksbehandling/steg/sats/Sats.tsx

Remove logic based on saksbehandlers input when showing information from søknad for sats

Vise korrekt informasjon fra søknaden for vurdering av Sats

---

src/pages/saksbehandling/steg/faktablokk/faktablokker/FormueFaktablokk.tsx
src/pages/saksbehandling/steg/formue/Formue.tsx
src/pages/saksbehandling/steg/formue/formue-nb.ts
src/pages/saksbehandling/vilkårsOppsummering/VilkårsOppsummering.tsx

Spørsmålet om søker bor med en ektefelle og evt. hva fødselsnummeret er hadde gått i den såkalte glømmebokji.

Vis saksbehandlers valg om ektefelle i oppsummeringen

---

.github/workflows/branch.yml
server/start.ts
src/Root.tsx
src/api/featureToggleApi.ts
src/lib/tracking/hotjar.ts

Legger til Hotjar, og feature toggler det slik at vi evt. kan teste i testmiljøet dersom vi finner noen løsning på hvordan Hotjar kan få tilgang til CSS og lage nyttige screenshots.

Sett opp tracking med Hotjar

---

src/features/behandling/behandlingUtils.ts
src/features/saksoversikt/utils.tsx
src/pages/saksbehandling/steg/formue/Formue.tsx
src/pages/saksbehandling/steg/sats/Sats.tsx
src/types/Behandlingsinformasjon.ts

Co-authored-by: John Andre Hestad <john.andre.hestad@nav.no>
Vi har i samme slengen fjernet epsAlder i bositasjon json.

Resetting sats when changing EPS in formue. fixed fremdriftsindikator

---

src/features/saksoversikt/utils.tsx
src/pages/attestering/attesterBehandling/AttesterBehandling.tsx
src/pages/attestering/attesterBehandling/attestering-nb.ts
src/pages/saksbehandling/behandlingsoppsummering/behandlingsoppsummering-nb.ts
src/pages/saksbehandling/behandlingsoppsummering/behandlingsoppsummering.tsx
src/pages/saksbehandling/steg/beregningOgSimulering/beregning/Beregning.tsx
src/pages/saksbehandling/steg/beregningOgSimulering/beregning/beregning-nb.ts

kunne kanskje ha sett på å forenkle fremdriftsindiaktoren for sats på. Men tenker å bare få den inn for å få det til å virke etter at vi fikset buggen

fix - sats fremdriftsindikator. default feil når kall feiler

---

src/api/pdfApi.ts
src/api/revurderingApi.ts
src/features/revurdering/revurderingActions.ts
src/features/saksoversikt/sak.slice.ts
src/pages/attestering/attesterRevurdering/AttesterRevurdering.tsx
src/pages/attestering/attesterRevurdering/attesterRevurdering-nb.ts
src/pages/attestering/attesterRevurdering/attesterRevurdering.module.less
src/pages/saksbehandling/behandlingsoppsummering/behandlingsoppsummering.tsx
src/pages/saksbehandling/revurdering/oppsummering/RevurderingsOppsummering.tsx
src/pages/søknad/kvittering/Kvittering.tsx

Avhenger av https://github.com/navikt/su-se-bakover/pull/235

Legg til knapp for forhåndsvisning av revurderingsbrev for attestant

---

src/api/apiClient.ts
src/api/behandlingApi.ts
src/api/pdfApi.ts
src/features/saksoversikt/sak.slice.ts
src/pages/attestering/attesterBehandling/AttesterBehandling.tsx
src/pages/saksbehandling/behandlingsoppsummering/behandlingsoppsummering.tsx
src/pages/saksbehandling/revurdering/oppsummering/RevurderingsOppsummering.tsx
src/pages/saksbehandling/vedtak/Vedtak.tsx
src/pages/saksbehandling/vedtak/vedtak-nb.ts
src/pages/saksbehandling/vedtak/vedtak.module.less

Avhenger av https://github.com/navikt/su-se-bakover/pull/239

Legg til støtte for fritekst i søknadsbehandlingbrev

---

src/pages/saksbehandling/revurdering/Revurdering.tsx
src/pages/saksbehandling/revurdering/oppsummering/RevurderingsOppsummering.tsx
src/pages/saksbehandling/revurdering/oppsummering/revurderingOppsummering-nb.ts
src/pages/saksbehandling/revurdering/oppsummering/revurderingsOppsummering.module.less
src/pages/saksbehandling/revurdering/revurderingUtils.ts
src/types/Revurdering.ts

Revurdering ingen endring status

---

src/pages/søknad/kvittering/Kvittering.tsx

bare til å ignorere den biten der jeg gjorde en commit inn til master som gjorde 50% av oppgaven ved en feil 😅 fortsatt ferie modus

Naviger saksbehandler til saksoversiktsiden etter hen har avsluttet en søknad

---

src/pages/attestering/attesterRevurdering/AttesterRevurdering.tsx
src/pages/attestering/attesterRevurdering/attesterRevurdering-nb.ts
src/pages/attestering/attesterRevurdering/attesterRevurdering.module.less

Co-authored-by: Ingar Almklov <ingara@gmail.com>
Co-authored-by: Christian H. Mosveen <christian.mosveen@nav.no>

Fiks sånn at saksoversikt oppdateres etter å ha innvilget en revurdering

---

src/pages/saksbehandling/revurdering/oppsummering/RevurderingsOppsummering.tsx
src/pages/saksbehandling/steg/beregningOgSimulering/beregning/visBeregning.module.less
src/pages/saksbehandling/steg/beregningOgSimulering/simulering/simulering-nb.ts
src/pages/saksbehandling/steg/beregningOgSimulering/simulering/simulering.tsx
src/pages/vedtak/Vedtaksoppsummering.tsx
src/pages/vedtak/vedtaksoppsummering.module.less
src/types/Revurdering.ts
src/types/Simulering.ts
src/types/Vedtak.ts

Avhenger av https://github.com/navikt/su-se-bakover/pull/259

Vis om en periode i en simulering er en etterbetaling, feilutbetaling, ordinær utbetaling, uendret eller gir ingen utbetaling

---

Dockerfile
nais.yml

Co-authored-by: Christian H. Mosveen <mosveen@gmail.com>
Co-authored-by: Richard Martinsen <github@martinsen.org>

Fiks oppstart av applikasjon på Nais

---

src/pages/saksbehandling/steg/beregningOgSimulering/beregning/VisBeregning.tsx
src/pages/saksbehandling/steg/beregningOgSimulering/beregning/visBeregning.module.less

Har endret så att dom-strukturen ska matcha det nya opplägget for visning av en beregning:

Fix av visning av fradragen i beregning

---

src/pages/saksbehandling/revurdering/revurderingskallFeilet/RevurderingskallFeilet.tsx
src/pages/saksbehandling/revurdering/revurderingskallFeilet/revurderingskallFeilet-nb.ts
src/types/Revurdering.ts

Med tanke på at denne bare fjernet en error code som back-end ikke lenger bruker, så tar jeg friheten og merger rett til master 😎

rmv unused error code

---

src/pages/saksbehandling/steg/beregningOgSimulering/beregning/VisBeregning.tsx

Co-authored-by: ramziabuqassim <ramzi.abu.qassim@nav.no>

Fiks feil i visning av inntekt for eps

---

src/pages/saksbehandling/revurdering/revurderingskallFeilet/RevurderingskallFeilet.tsx
src/pages/saksbehandling/revurdering/revurderingskallFeilet/revurderingskallFeilet-nb.ts
src/pages/saksbehandling/revurdering/uførhet/Uførhet.tsx
src/types/Revurdering.ts

Co-authored-by: Ingar Almklov <ingara@gmail.com>

Ikke lov å velge "nei" for vilkår ved g-regulering + feilmeldinger.

---

src/pages/saksbehandling/revurdering/uførhet/Uførhet.tsx

Co-authored-by: ramziabuqassim <ramzi.abu.qassim@nav.no>

Fiks bug der saksbehandler ikke kunne endre på forventetInntekt til 0

---

src/api/revurderingApi.ts
src/features/revurdering/revurderingActions.ts
src/features/revurdering/sharedMessages-nb.ts
src/pages/saksbehandling/revurdering/Revurdering.tsx
src/pages/saksbehandling/revurdering/oppsummering/EtterForhåndsvarsel.tsx
src/pages/saksbehandling/revurdering/oppsummering/Forhåndsvarsel.tsx
src/pages/saksbehandling/revurdering/oppsummering/GReguleringForOppsummering.tsx
src/pages/saksbehandling/revurdering/oppsummering/IngenEndring.tsx
src/pages/saksbehandling/revurdering/oppsummering/RevurderingsOppsummering.tsx
src/pages/saksbehandling/revurdering/oppsummering/SendRevurderingTilAttesteringForm.tsx
src/pages/saksbehandling/revurdering/oppsummering/revurderingOppsummering-nb.ts
src/pages/saksbehandling/revurdering/revurderingIntro/EndreRevurderingPage.tsx
src/pages/saksbehandling/revurdering/revurderingIntro/NyRevurderingPage.tsx
src/pages/saksbehandling/revurdering/revurderingIntro/RevurderingIntroForm.tsx
src/pages/saksbehandling/revurdering/revurderingIntro/revurderingIntro-nb.ts
src/pages/saksbehandling/revurdering/revurderingUtils.ts
src/pages/saksbehandling/sakintro/Sakintro.tsx
src/types/Revurdering.ts

Avhenger av https://github.com/navikt/su-se-bakover/pull/296

Muliggjør å velge hvilke ting man har lyst til å revurdere

---

src/pages/søknad/steg/bo-og-opphold-i-norge/EktefellePartnerSamboer.tsx
src/pages/søknad/steg/bo-og-opphold-i-norge/bo-og-opphold-i-norge-nb.ts
src/pages/søknad/steg/bo-og-opphold-i-norge/utils.ts
src/types/Søknad.ts

lagt til spinner og feil for EPS-personsøk

sender ikke EPS som null dersom EPS over 67 år

---

src/components/revurdering/RevurderingIngenEndringAlert.tsx
src/features/revurdering/sharedMessages-nb.ts
src/pages/attestering/attesterRevurdering/AttesterRevurdering.tsx
src/pages/saksbehandling/revurdering/oppsummering/RevurderingsOppsummering.tsx
src/pages/saksbehandling/revurdering/oppsummering/SendRevurderingTilAttesteringForm.tsx
src/pages/saksbehandling/revurdering/revurderingUtils.ts

fiks typer på noen av utils funksjoner

får beskjed når g-regulering faller i ingen-endring

---

src/api/revurderingApi.ts
src/features/revurdering/revurderingActions.ts
src/features/saksoversikt/sak.slice.ts
src/pages/saksbehandling/revurdering/oppsummering/RevurderingsOppsummering.tsx
src/pages/saksbehandling/revurdering/revurderingskallFeilet/RevurderingskallFeilet.tsx
src/pages/saksbehandling/revurdering/revurderingskallFeilet/revurderingskallFeilet-nb.ts
src/types/Revurdering.ts

-Ny respons
-Visning av feilmeldinger for utfall som ikke støttes
Se sammenheng med backend: https://github.com/navikt/su-se-bakover/pull/324

Endringer for å håndtere ny respons fra beregn/simuler

---

src/api/personApi.ts
src/api/sakApi.ts

Se https://github.com/navikt/su-se-bakover/pull/329 for API-endring

Bruk POST i stedet for GET for kall med fnr

---

server/start.ts
src/components/ErrorBoundary.tsx
src/pages/drift/index.tsx

Og lagd en knapp på Driftssiden som trigger en feil for å kunne teste Sentry.

Tillat kall til Sentry via CSP

---

src/pages/attestering/attesterBehandlingPage/AttesterBehandlingPage.tsx
src/types/Behandling.ts

Bug fiks: Revurderingsknappen og stønadsperioder etc døk ikke opp etter man iverksatt en behandling

Oppdater sak etter man har iverksatt behandling

---

src/api/søknadApi.ts
src/pages/søknad/index.tsx

Avhengig av: https://github.com/navikt/su-se-bakover/pull/369

Send bruker til startsiden hvis auth-token har utløpt

---

src/api/revurderingApi.ts
src/features/revurdering/revurderingoppsummering/Revurderingoppsummering.tsx
src/pages/attestering/attesterRevurdering/AttesterRevurdering.tsx
src/pages/saksbehandling/revurdering/OppsummeringPage/RevurderingOppsummeringPage.tsx
src/pages/vedtak/Vedtaksoppsummering.tsx
src/pages/vedtak/utils.ts
src/pages/vedtak/vedtaksoppsummering-nb.ts
src/pages/vedtak/vedtaksoppsummering.module.less

Avhengig av: https://github.com/navikt/su-se-bakover/pull/377

Vis oppsummering for revurderingsvedtak

---

src/lib/featureToggles.tsx

Dette er en situasjon som typisk oppstår i test når man mister tilgang til naisdevice. Siden disse var uhåndterte feil blir de plukket opp av sentry og postet dit, noe som fører til mye støy siden vi henter feature toggles relativt ofte.

Håndter nettverksfeil når vi henter feature toggles

---

src/pages/saksbehandling/restans/Restanser.tsx
src/pages/saksbehandling/søknadsbehandling/formue/Formue.tsx
src/pages/saksbehandling/søknadsbehandling/types.ts
src/pages/saksbehandling/søknadsbehandling/vilkår/Vilkår.tsx

søker man en person som ikke har sak, så henter sak fra tabell, vil feil navn vises

fiks at feil navn kan vises i personlinje

---

src/components/revurdering/oppsummering/oppsummeringsblokk/Oppsummeringsblokk.tsx
src/components/revurdering/oppsummering/oppsummeringsblokk/oppsummeringsblokk.module.less
src/components/søknadsbehandlingoppsummering/SøknadsbehandlingHeader.tsx
src/components/søknadsbehandlingoppsummering/søknadsbehandling-nb.ts
src/components/søknadsbehandlingoppsummering/søknadsbehandlingHeader.module.less
src/components/underkjenteAttesteringer/UnderkjenteAttesteringer.tsx
src/components/underkjenteAttesteringer/underkjenteAttestering-nb.ts
src/components/underkjenteAttesteringer/underkjenteAttesteringer.module.less
src/pages/drift/index.module.less
src/pages/saksbehandling/attestering/attesterRevurdering/AttesterRevurdering.tsx
src/pages/saksbehandling/attestering/attesterSøknadsbehandling/AttesterSøknadsbehandling.tsx
src/pages/saksbehandling/attestering/sharedStyles.module.less
src/pages/saksbehandling/revurdering/OppsummeringPage/RevurderingOppsummeringPage.tsx
src/pages/saksbehandling/sakintro/Sakintro.tsx
src/pages/saksbehandling/sakintro/sakintro-nb.ts
src/pages/saksbehandling/sakintro/sakintro.module.less
src/pages/saksbehandling/saksoversikt.module.less
src/utils/revurdering/revurderingUtils.ts

Alle oppsummeringssider av søknadsbehandling og revurdering skal nå vise alle underkjenninger på behandlingen.

Vis underkjenninger på alle oppsummeringssider

---

package-lock.json
package.json
src/components/TextProvider.tsx
src/index.js
src/polyfills.ts
src/utils/date/dateUtils.ts
src/utils/format/formatUtils.ts

Se disse for mer detaljer:
- https://github.com/formatjs/formatjs/issues/3066
- https://bugs.chromium.org/p/chromium/issues/detail?id=1215606&q=norwegian&can=2

Fiks manglende norsk locale i Chrome 92

---

src/components/revurdering/oppsummering/vedtaksinformasjon/grunnlagsblokker.ts

Bug fiks: Står "Ja" istället för "Nej" 😊

Fiks typo med ektefelle ufør flyktning oppsummering

---

src/components/beregningOgSimulering/beregning/Beregning.tsx
src/components/beregningOgSimulering/beregning/beregning-nb.ts
src/components/revurdering/revurderingskallFeilet/RevurderingskallFeilet.tsx
src/components/revurdering/revurderingskallFeilet/revurderingskallFeilet-nb.ts
src/features/revurdering/sharedMessages-nb.ts
src/pages/saksbehandling/attestering/attesterSøknadsbehandling/AttesterSøknadsbehandling.tsx
src/types/Revurdering.ts

Backend-endringer: https://github.com/navikt/su-se-bakover/pull/414

Legg til spesifikke feilmeldinger for de vanligste simuleringsfeilene

---

src/components/Personsøk/Personsøk.tsx
src/components/Personsøk/personsøk.module.less
src/pages/saksbehandling/Saksoversikt.tsx
src/pages/saksbehandling/restans/Restanser.tsx
src/pages/saksbehandling/restans/restanser-nb.ts
src/pages/saksbehandling/restans/restanserUtils.ts
src/pages/saksbehandling/saksoversikt.module.less
src/pages/søknad/steg/inngang/inngang.module.less
src/types/Restans.ts

Skrudd på igjen etter implementering av designendringene

Vis liste av åpne behandlinger

---

src/lib/validering.ts

Denne er brukt i formuesteget i søknadsbehandling og i uføresteget i revurdering.

Bruk en raskere måte å validere strenger som tall på

---

src/components/beregningOgSimulering/beregning/Beregning.tsx
src/components/beregningOgSimulering/beregning/beregning-nb.ts
src/components/revurdering/revurderingskallFeilet/RevurderingskallFeilet.tsx
src/components/revurdering/revurderingskallFeilet/revurderingskallFeilet-nb.ts
src/types/Revurdering.ts

Konsoliderer også feilkodene med hva som blir gjort i https://github.com/navikt/su-se-bakover/pull/438

Legg til feilmelding om simuleringsfeil pga. at oppdraget ikke finnes

---

package-lock.json
package.json
src/lib/hooks.ts
src/pages/saksbehandling/søknadsbehandling/fast-opphold-i-norge/FastOppholdINorge.tsx
src/pages/saksbehandling/søknadsbehandling/flyktning/Flyktning.tsx
src/pages/saksbehandling/søknadsbehandling/formue/Formue.tsx
src/pages/saksbehandling/søknadsbehandling/institusjonsopphold/Institusjonsopphold.tsx
src/pages/saksbehandling/søknadsbehandling/lovlig-opphold-i-norge/LovligOppholdINorge.tsx
src/pages/saksbehandling/søknadsbehandling/opphold-i-utlandet/OppholdIUtlandet.tsx
src/pages/saksbehandling/søknadsbehandling/personlig-oppmøte/PersonligOppmøte.tsx
src/pages/saksbehandling/søknadsbehandling/sats/Sats.tsx
src/pages/saksbehandling/søknadsbehandling/uførhet/Uførhet.tsx

Unngår timingproblem som resulterer i at vi blinker validerings-kontaineren.

Bruk async/await på alle neste/lagre-handlinger

---

src/components/beregningOgSimulering/beregning/Beregning.tsx

Evig loop med når beregning var avslag så kunde vi ikke gå videre og bad om ny beregning.

Fiks bug med beregning avslag

---

src/pages/saksbehandling/revurdering/formue/Formue.tsx
src/pages/saksbehandling/revurdering/formue/formueUtils.ts

tilOgMed sendes som siste dag i måneden

---

src/components/revurdering/revurderingskallFeilet/RevurderingskallFeilet.tsx
src/components/revurdering/revurderingskallFeilet/revurderingskallFeilet-nb.ts
src/pages/saksbehandling/revurdering/uførhet/Uførhet.tsx
src/types/Revurdering.ts

backend: https://github.com/navikt/su-se-bakover/pull/460/files

rydd opp i feilkoder

---

src/Root.less
src/assets/Illustrations.tsx
src/components/beregningOgSimulering/beregning/fradragInputs.module.less
src/lib/routes.ts
src/pages/saksbehandling/Saksoversikt.tsx
src/pages/saksbehandling/dokumenter/DokumenterPage.tsx
src/pages/saksbehandling/dokumenter/dokumenterPage-nb.ts
src/pages/saksbehandling/dokumenter/dokumenterPage.module.less
src/pages/saksbehandling/revurdering/formue/formue.module.less
src/pages/saksbehandling/revurdering/uførhet/uførhet.module.less
src/pages/saksbehandling/sakintro/Sakintro.tsx
src/pages/saksbehandling/sakintro/sakintro-nb.ts
src/pages/saksbehandling/sakintro/sakintro.module.less
src/pages/saksbehandling/saksoversikt.module.less
src/pages/saksbehandling/søknadsbehandling/formue/formue.module.less

Gikk i samme slengen, etter å ha snakket med designerne, over og endret kroppbakgrunnsfargen til å være lysegrå.

Legg til side for å liste ut alle brev sendt fra SU

---

src/pages/saksbehandling/revurdering/formue/formueUtils.ts

Den kopierte forrige verdier som var lagt in

ny formue-periode skal alltid starte tom

---

src/components/apiErrorAlert/søknadsbehandlingApiError/SøknadsbehandlingApiError.ts
src/components/apiErrorAlert/søknadsbehandlingApiError/søknadsbehandlingApiError-nb.ts

Denne ga bare "Ukjent feil" nå.

Legg til feilmelding hvis stønadsperiode overlapper eksisterende

---

src/lib/validering.ts
src/pages/saksbehandling/søknadsbehandling/formue/Formue.tsx

Denne stoppet før på en generell "ugyldige_verdier_på_formue" fra backend.

Validér at depositum er mindre eller lik innskudd

---

src/pages/saksbehandling/revurdering/OppsummeringPage/RevurderingOppsummeringPage.tsx
src/pages/saksbehandling/revurdering/OppsummeringPage/oppsummeringPageForms/OppsummeringPageForms.tsx
src/pages/saksbehandling/søknadsbehandling/sendTilAttesteringPage/SendTilAttesteringPage.tsx
src/types/Behandling.ts

Avhenger av https://github.com/navikt/su-se-bakover/pull/497

Behold fritekst til brev etter attestering

---

src/pages/saksbehandling/dokumenter/DokumenterPage.tsx
src/pages/saksbehandling/dokumenter/dokumenterPage.module.less
src/types/dokument/Dokument.ts

Viser om et brev er journalført og sendt til saksbehandler
Avhenger av https://github.com/navikt/su-se-bakover/pull/543

Vise status på brev i form av brevSendt og journalført

---

README.md
start-dev.sh

Docker har tatt inn compose under vingene sine som sin egen plugin.

Bytt fra docker-compose til docker compose

---

src/api/personApi.ts
src/api/sakApi.ts
src/components/Personsøk/Personsøk.tsx
src/components/apiErrorAlert/ApiErrorAlert-nb.ts
src/components/apiErrorAlert/ApiErrorAlertUtils.ts
src/pages/søknad/steg/inngang/Inngang.tsx
src/pages/søknad/steg/inngang/inngang-nb.ts
src/types/Sak.ts
src/utils/søknad/søknadUtils.ts

Avhenger av https://github.com/navikt/su-se-bakover/pull/546

Søknadinngang: hent kun nødvendig informasjon om saken

---

src/api/behandlingApi.ts
src/features/saksoversikt/sak.slice.ts
src/pages/saksbehandling/søknadsbehandling/formue/Formue.tsx

Gjør dette som et eget API-kall, for å ikke blande det inn med at lagringen også oppdaterer behandlingsinformasjon
https://github.com/navikt/su-se-bakover/pull/555

Lagre EPS med adressebeskyttelse eller skjerming

---

src/api/revurderingApi.ts
src/features/revurdering/revurderingActions.ts
src/features/saksoversikt/sak.slice.ts
src/pages/saksbehandling/revurdering/OppsummeringPage/RevurderingOppsummeringPage.tsx
src/pages/saksbehandling/revurdering/OppsummeringPage/oppsummeringPageForms/OppsummeringPageForms.tsx

Avhenger av https://github.com/navikt/su-se-bakover/pull/570

Splitt lagring av forhåndsvarsel og sending til attestering

---

src/pages/saksbehandling/søknadsbehandling/virkningstidspunkt/Virkningstidspunkt.tsx
src/pages/saksbehandling/søknadsbehandling/virkningstidspunkt/virkningstidspunkt-nb.ts
src/pages/saksbehandling/søknadsbehandling/virkningstidspunkt/virkningstidspunkt.module.less
src/pages/søknad/steg/inngang/Inngang.tsx
src/pages/søknad/steg/inngang/inngang-nb.ts
src/pages/søknad/steg/inngang/inngang.module.less
src/utils/person/personUtils.ts

Saksbehandling:
Søknad:
Søknad med flere alerts:

Advarsel om alder i søknad og saksbehandling

---

src/pages/saksbehandling/søknadsbehandling/virkningstidspunkt/Virkningstidspunkt.tsx
src/pages/søknad/steg/inngang/Inngang.tsx
src/pages/søknad/steg/inngang/inngang-nb.ts
src/utils/person/personUtils.ts

Legg til url og vis for 67 og eldre

---

src/api/kontrollsamtaleApi.ts
src/api/sakApi.ts
src/pages/saksbehandling/dokumenter/DokumenterPage.tsx
src/pages/saksbehandling/dokumenter/dokumenterPage-nb.ts
src/pages/saksbehandling/dokumenter/dokumenterPage.module.less

Sender et innkallingsbrev til bruker, og refresher listen med brev som en slags enkel status.
https://github.com/navikt/su-se-bakover/pull/577

Kall inn til kontrollsamtale

---

src/pages/nøkkeltall/index.tsx
src/pages/nøkkeltall/nøkkeltall-nb.ts
src/types/Nøkkeltall.ts

Backend: https://github.com/navikt/su-se-bakover/pull/588

Vis nøkkeltall for løpende saker

---

src/components/Personsøk/Personsøk.tsx

Viser også bare valideringsfeil-diven dersom det faktisk er noe feil, slik at skjønnhetsflekken forsvinner.

Forenkle validering for personsøk

---

src/components/revurdering/oppsummering/formuevilkåroppsummering/FormuevilkårOppsummering.tsx
src/components/revurdering/oppsummering/formuevilkåroppsummering/formuevilkåroppsummering-nb.ts
src/components/revurdering/oppsummering/formuevilkåroppsummering/formuevilkåroppsummering.module.less
src/components/revurdering/oppsummering/oppsummeringspar/Oppsummeringspar.tsx
src/components/revurdering/oppsummering/oppsummeringspar/Oppsummeringsverdi.tsx
src/components/revurdering/oppsummering/utenlandsopphold/Utenlandsoppsummering.tsx
src/components/revurdering/oppsummering/vedtaksinformasjon/Vedtaksinformasjon.tsx
src/pages/saksbehandling/revurdering/bosituasjon/BosituasjonFormPage.tsx

Fikse formue-oppsummering for eps

---

src/api/revurderingApi.ts
src/components/apiErrorAlert/ApiErrorAlert-nb.ts
src/components/apiErrorAlert/apiErrorCode.ts
src/features/revurdering/revurderingActions.ts
src/pages/saksbehandling/revurdering/OppsummeringPage/RevurderingOppsummeringPage.tsx

https://trello.com/c/5iblmYP9/1090-endre-sperre-for-10-endring-til-%C3%A5-v%C3%A6re-en-advarsel
https://github.com/navikt/su-se-bakover/pull/641

Vis varselmelding ved beløpsendring under 10%

---

src/pages/søknad/steg/formue/epsFormue/EktefellesFormue.tsx
src/pages/søknad/steg/formue/søkersFormue/DinFormue.tsx
src/pages/søknad/steg/oppsummering/components/FormueOppsummering.tsx

Ref: https://trello.com/c/JoGqzxYp/1095-spm-om-eier-du-andre-eiendommer-i-norge-eller-andre-land-forsvinner-n%C3%A5r-du-krysser-av-nei-p%C3%A5-spm-eier-du-bolig

Vis spm. om andre eiendommer i formue uavhengig av søker eier bolig

---

src/pages/klage/vurderFormkrav/vurderFormkrav-nb.ts
src/types/Vedtak.ts

Merges sammen med: https://github.com/navikt/su-se-bakover/pull/650

Legg til klagevedtak

---

src/components/datePicker/DatePicker.tsx
src/components/datePicker/datePicker.module.less
src/components/oppsummeringAvKlage/OppsummeringAvKlage.tsx
src/components/oppsummeringAvKlage/oppsummeringAvKlage-nb.ts
src/components/oppsummeringAvKlage/oppsummeringAvKlage.module.less
src/components/revurdering/oppsummering/oppsummeringspar/Oppsummeringsverdi.tsx
src/pages/klage/klage-nb.ts
src/pages/klage/opprettKlage/OpprettKlage.tsx
src/pages/saksbehandling/attestering/attesterKlage/AttesterKlage.tsx
src/pages/saksbehandling/attestering/attesterKlage/attesterKlage.module.less
src/pages/saksbehandling/sakintro/KlageLister.tsx
src/pages/saksbehandling/sakintro/Sakintro.tsx
src/pages/saksbehandling/sakintro/sakintro-nb.ts
src/pages/saksbehandling/vedtak/Vedtaksoppsummering.tsx
src/pages/saksbehandling/vedtak/klagevedtaksoppsummering/klagevedtaksoppsummering.module.less
src/pages/saksbehandling/vedtak/klagevedtaksoppsummering/klagevedtaksoppsummering.tsx
src/pages/saksbehandling/vedtak/utils.ts
src/utils/klage/klageUtils.ts

PR:en består av:
* Funksjonalitet for å vise oppsummeringen av ferdigbehandlede klager
* Litt bugfikses knyttet til oppsummeringsvisningen av klage
* Funksjonalitet for datepicker å vise hjelpetekst bredvid label & lagt til hjelpetekst for spørsmål kring mottaks dato av klagen

Klagevedtak oppsummering

---

src/api/apiClient.ts
src/pages/klage/vurderingAvKlage/VurderingAvKlage-nb.ts
src/types/Klage.ts

Ikke merge denne før Kabal har lagt til hjemlene først.
Merges sammen med https://github.com/navikt/su-se-bakover/pull/662

Legg til klagehjemlene 11, 17 og 21

---

src/api/driftApi.ts
src/pages/drift/components/GReguleringTabell.tsx
src/pages/drift/index.tsx
src/types/GRegulering.ts
src/types/Regulering.ts

Del 0 av automatisk G-regulering, hvor vi kun prøver å få full oversikt over hvilke saker som kan G-reguleres automatisk og hvilke som må til manuell regulering.

Oversikt i driftssiden for g-regulering

---

src/components/apiErrorAlert/ApiErrorAlert-nb.ts
src/components/apiErrorAlert/ApiErrorAlert.tsx
src/components/apiErrorAlert/apiErrorCode.ts
src/pages/saksbehandling/restans/Restanser.tsx
src/pages/saksbehandling/restans/restanser-nb.ts
src/pages/saksbehandling/restans/restanser.module.less
src/pages/saksbehandling/restans/restanserUtils.ts

Fjernet feilmelding under "se sak"-knappen, da den uansett vises under søkefeltet når vi søker etter en sak. Enn så lenge er denne tabellen kun brukt her, så er en liten quick-fix for å løse det egentlig

Ryddet litt i feilmeldinger for ferdige behandlinger

---

src/api/personApi.ts
src/components/personadvarsel/PersonAdvarsel.tsx
src/components/personadvarsel/personAdvarsel.module.less

vis dødsdato i personlinjen dersom personen er død

---

src/features/søknad/søknad.slice.ts
src/pages/søknad/steg/flyktningstatus-oppholdstillatelse/Flyktningstatus-oppholdstillatelse.tsx
src/pages/søknad/steg/formue/kjøretøyInputfelter/KjøretøyInputFelter.tsx
src/pages/søknad/steg/formue/søkersFormue/DinFormue.tsx

Erstatte formik med react hook form på to steg

Erstatt formik med react-hook-form på to steg

---

src/pages/søknad/steg/flyktningstatus-oppholdstillatelse/Flyktningstatus-oppholdstillatelse.tsx
src/pages/søknad/steg/formue/søkersFormue/DinFormue.tsx

useEffects hadde noen side-effects hva gjaldt frem og tilbake-navigering. Fix på dette her

Fix frem og tilbake-errors

---

src/components/oppsummeringAvKlage/OppsummeringAvKlage.tsx
src/components/oppsummeringAvKlage/oppsummeringAvKlage-nb.ts
src/components/oppsummeringAvKlage/oppsummeringAvKlage.module.less
src/pages/klage/vurderingAvKlage/VurderingAvKlage-nb.ts
src/pages/klage/vurderingAvKlage/VurderingAvKlage.tsx
src/pages/saksbehandling/attestering/attesterKlage/AttesterKlage.tsx
src/pages/saksbehandling/attestering/attesterKlage/attesterKlage-nb.ts
src/pages/saksbehandling/attestering/attesterKlage/attesterKlage.module.less

- Endre hjelpetekst på brev-input ved klage
- Gjør brev-input feltet større
- Legg på en 'Se brev' knapp på klage oppsummeringen

fiks små-ting ved klage

---

src/pages/saksbehandling/steg/uføre/UføreperiodeForm.tsx
src/pages/saksbehandling/steg/uføre/UførhetForm.tsx
src/pages/saksbehandling/steg/uføre/uførhet.module.less

Ny rekkefølge og preutfylle virkningstidspunkt

---

src/components/Personsøk/Personsøk.tsx

Personsøk-komponenten viste personen hvis man trykket "tilbake" i browser. Wiper person fra view og redux-state på mount av komponent

wipe person når man navigerer tilbake i browser

---

src/pages/søknad/steg/start-utfylling/StartUtfylling.tsx

Riktig styling for flyten i søknadsinnsendingen for preprod/prod

---

src/components/oppsummering/vilkårsOppsummering/faktablokk/faktablokker/BeregningFaktablokk.tsx
src/components/oppsummering/vilkårsOppsummering/faktablokk/faktablokker/faktablokker-nb.ts
src/features/søknad/søknad.slice.ts
src/features/søknad/utils.ts
src/pages/søknad/steg/inntekt/epsInntekt/EktefellesInntekt.tsx
src/pages/søknad/steg/inntekt/epsInntekt/inntekt-nb.ts
src/pages/søknad/steg/inntekt/inntektSøknadUtils.ts
src/pages/søknad/steg/inntekt/søkersInntekt/Inntekt.tsx
src/pages/søknad/steg/inntekt/søkersInntekt/inntekt-nb.ts
src/pages/søknad/steg/oppsummering/components/InntektsOppsummering.tsx
src/types/Søknad.ts

Henger sammen med https://github.com/navikt/su-se-bakover/pull/728 og https://github.com/navikt/su-pdfgen/pull/49

Fjern sosialstønadspørsmål fra søknaden

---

src/pages/saksbehandling/attestering/attesterRevurdering/AttesterRevurdering.tsx
src/pages/saksbehandling/attestering/attesterRevurdering/attesterRevurdering-nb.ts
src/pages/saksbehandling/vedtak/Vedtaksoppsummering.tsx
src/pages/saksbehandling/vedtak/revurderingsvedtakWithSnapshot/RevurderingsoppsummeringWithSnapshot.tsx
src/pages/saksbehandling/vedtak/revurderingsvedtakWithSnapshot/revurderingsoppsummeringWithSnapshot.module.less
src/pages/saksbehandling/vedtak/vedtaksoppsummering-nb.ts

La til alert på attestant og iverksettet-viewet
Attestant
Iverksettet (se oppsummering)

Vis til attestant at det skjer tilbakekreving

---

src/pages/saksbehandling/revurdering/OppsummeringPage/RevurderingOppsummeringPage.tsx
src/pages/saksbehandling/revurdering/OppsummeringPage/forhåndsvarsel/ForhåndsvarselForm.tsx
src/pages/saksbehandling/revurdering/OppsummeringPage/oppsummeringPageForms/OppsummeringPageForms.tsx
src/pages/saksbehandling/revurdering/OppsummeringPage/oppsummeringPageForms/oppsummeringPageForms-nb.ts
src/pages/saksbehandling/revurdering/OppsummeringPage/tilbakekreving/TilbakekrevingForm.tsx

Skal vise en forhåndsbestemt tekst ved tilbakekreving. La på validering som sjekker at ____ er byttet ut

Tilbakekreving - Preutfylt tekst for vedtaksbrev

---

src/pages/saksbehandling/attestering/attesterRevurdering/AttesterRevurdering.tsx
src/pages/saksbehandling/attestering/attesterRevurdering/attesterRevurdering-nb.ts
src/pages/saksbehandling/revurdering/OppsummeringPage/RevurderingOppsummeringPage.tsx
src/pages/saksbehandling/revurdering/OppsummeringPage/forhåndsvarsel/ForhåndsvarselForm.tsx
src/pages/saksbehandling/revurdering/OppsummeringPage/oppsummeringPageForms/OppsummeringPageForms.tsx
src/pages/saksbehandling/revurdering/OppsummeringPage/revurderingOppsummeringPage-nb.ts
src/pages/saksbehandling/revurdering/OppsummeringPage/revurderingOppsummeringsPageUtils.ts
src/pages/saksbehandling/revurdering/OppsummeringPage/tilbakekreving/TilbakekrevingForm.tsx
src/pages/saksbehandling/revurdering/OppsummeringPage/tilbakekreving/tilbakekrevingForm-nb.ts
src/pages/saksbehandling/vedtak/Vedtaksoppsummering.tsx
src/utils/revurdering/revurderingUtils.ts

* Legge til varsel om at det kun sendes ut tilbakekrevingsbrev - og ikke brev om endringer
* Gi muligheten til å _ikke_ sende ut forhåndsvarsel ved tilbakekreving

Varsel tilbakekreving

---

package-lock.json
package.json
src/Root.tsx
src/lib/routes.ts
src/pages/klage/Klage.tsx
src/pages/saksbehandling/Saksoversikt.tsx
src/pages/saksbehandling/attestering/Attestering.tsx
src/pages/saksbehandling/behandlingsoversikt/Behandlingsoversikt.tsx
src/pages/saksbehandling/revurdering/Revurdering.tsx
src/pages/saksbehandling/sakintro/SøknadsLister.tsx
src/pages/saksbehandling/sakintro/Utbetalinger.tsx
src/pages/saksbehandling/stans/Stans.tsx
src/pages/saksbehandling/stans/gjenoppta/gjenoppta.tsx
src/pages/saksbehandling/stans/gjenoppta/gjenopptaOppsummering.tsx
src/pages/saksbehandling/stans/stansOppsummering.tsx
src/pages/saksbehandling/søknadsbehandling/sats/Sats.tsx
src/pages/saksbehandling/søknadsbehandling/vilkår/Vilkår.tsx
src/pages/søknad/index.tsx

This reverts commit 9ad775b0f0a643a73dbec88450c01e8a554c198f.

Revert "React router 6 (#1781)"

---

package-lock.json
package.json
src/Root.tsx
src/lib/routes.ts
src/pages/klage/Klage.tsx
src/pages/saksbehandling/Saksoversikt.tsx
src/pages/saksbehandling/attestering/Attestering.tsx
src/pages/saksbehandling/behandlingsoversikt/Behandlingsoversikt.tsx
src/pages/saksbehandling/revurdering/Revurdering.tsx
src/pages/saksbehandling/sakintro/SøknadsLister.tsx
src/pages/saksbehandling/sakintro/Utbetalinger.tsx
src/pages/saksbehandling/stans/Stans.tsx
src/pages/saksbehandling/stans/gjenoppta/gjenoppta.tsx
src/pages/saksbehandling/stans/gjenoppta/gjenopptaOppsummering.tsx
src/pages/saksbehandling/stans/stansOppsummering.tsx
src/pages/saksbehandling/søknadsbehandling/sats/Sats.tsx
src/pages/saksbehandling/søknadsbehandling/vilkår/Vilkår.tsx
src/pages/søknad/index.tsx

Nytt forsøk på steg 1 av migrering til React Router v2
* setup router compatibility package
* use CompatRoute
* Erstatte Route med CombatRoute. Ser ikke ut som at CombatRoute med Switch inne i seg og nytt lag med CombatRoute fungerer
* Fix behandlingsoversikt søk etter fnr bug

React router 6 (#1781) Step 1

---

src/Root.tsx
src/components/beregningOgSimulering/beregning/Beregning.tsx
src/components/personlinje/Personlinje.tsx
src/components/revurdering/oppsummering/oppsummeringsblokk/Oppsummeringsblokk.tsx
src/pages/saksbehandling/dokumenter/DokumenterPage.tsx
src/pages/saksbehandling/revurdering/Revurdering.tsx
src/pages/saksbehandling/vedtak/reguleringsvedtaksoppsummering/reguleringVedtaksoppsummering.tsx
src/pages/søknad/kvittering/Kvittering.tsx
src/pages/søknad/steg/inngang/Inngang.tsx
src/utils/array/arrayUtils.ts
src/utils/klage/klageUtils.ts
src/utils/revurdering/revurderingUtils.ts

Fikk module not found-feil i preprod. Sett den en gang før, men vet ikke helt hvorfor det kommer. Det har med kompilering og imports å gjøre, men fortstår ikke noe mer enn det.
Fixen ble å kjøre samme import-path for pipe overalt. Dvs bruke vår egen implementerte pipe
EDIT: Ser ut som at det er lazy-import som fucker opp. Fjerna lazy-import på attestering slik at det funker nå. Må undersøke videre hva som er best håndtering her

fix import

---

src/components/apiErrorAlert/ApiErrorAlert-nb.ts
src/components/apiErrorAlert/apiErrorCode.ts
src/pages/saksbehandling/sakintro/ReguleringLister.tsx
src/pages/saksbehandling/sakintro/sakintro-nb.ts
src/pages/saksbehandling/sakintro/sakintro.module.less

+ bugfiks: viser ikke "Se oppsummering" på reguleringer som blitt avsluttet.

Legg til Modal når du skal avslutte regulering

---

src/Root.tsx
src/api/søknadApi.ts
src/components/header/Header.tsx
src/features/søknad/innsending.slice.ts
src/features/søknad/søknad.slice.ts
src/features/søknad/utils.ts
src/lib/featureToggles.tsx
src/lib/routes.ts
src/pages/søknad/Søknadsvelger.tsx
src/pages/søknad/index.tsx
src/pages/søknad/nb.ts
src/pages/søknad/steg/Steg.tsx
src/pages/søknad/steg/alderspensjon/Alderspensjon.tsx
src/pages/søknad/steg/alderspensjon/alderspensjon-nb.ts
src/pages/søknad/steg/flyktningstatus-oppholdstillatelse/flyktningstatus-oppholdstillatelse-nb.ts
src/pages/søknad/steg/infoside/Infoside.tsx
src/pages/søknad/steg/infoside/infoside-nb.ts
src/pages/søknad/steg/inngang/Inngang.tsx
src/pages/søknad/steg/oppholdstillatelse/Oppholdstillatelse.tsx
src/pages/søknad/steg/oppholdstillatelse/oppholdstillatelse-nb.ts
src/pages/søknad/steg/oppsummering/Oppsummering.tsx
src/pages/søknad/steg/oppsummering/Søknadoppsummering/Søknadoppsummering.tsx
src/pages/søknad/steg/oppsummering/Søknadoppsummering/søknadsoppsummering-nb.ts
src/pages/søknad/steg/oppsummering/components/EndreSvar.tsx
src/pages/søknad/steg/start-utfylling/StartUtfylling.tsx
src/pages/søknad/søknadsvelger.module.less
src/pages/søknad/types.ts
src/pages/søknad/utils.ts
src/types/Søknad.ts

Alderssøknad bak bryter
Man kan ikke sende inn, men alle stegene + oppsummering er på plass. Infoside og litt sånne ting må fikses, men tenker det er fint å få dette inn da det legger litt skjelett

Alderssøknad

---

src/features/søknad/søknad.slice.ts
src/features/søknad/utils.ts
src/pages/søknad/steg/bo-og-opphold-i-norge/Bo-og-opphold-i-norge.tsx
src/pages/søknad/steg/bo-og-opphold-i-norge/EktefellePartnerSamboer.tsx
src/pages/søknad/steg/bo-og-opphold-i-norge/bo-og-opphold-i-norge.module.less
src/pages/søknad/steg/bo-og-opphold-i-norge/scheme.ts
src/pages/søknad/steg/uførevedtak/Uførevedtak.tsx

Fjerne formik på to steg. Vi jobber mot å fase ut Formik (heller bruke react-hook-form) så dette er to nye steg på veien

Fjern formik

---

src/pages/saksbehandling/sakintro/utbetalinger-nb.ts
src/types/Utbetalingsperiode.ts

No more annoying feilmeldinger i consolen 🥳

Legg til utbetalingstyper som manglet

---

src/api/søknadApi.ts
src/features/søknad/innsending.slice.ts
src/features/søknad/utils.ts
src/lib/routes.ts
src/pages/søknad/steg/Steg.tsx
src/types/Søknad.ts

Tilpasse data fra søknaden til å matche det backend forventer

Alderssøknad til å matche backends signatur

---

src/pages/søknad/Søknadsvelger.tsx
src/pages/søknad/index.module.less
src/pages/søknad/index.tsx
src/pages/søknad/nb.ts
src/pages/søknad/søknadsvelger.module.less
src/pages/søknad/types.ts

I stedet for de enkle knappene som var der før er det nå lagt på veilendende
tekst og beskrivelse av løsningene.
For å se endringene må feature'en ALDERSØKNAD_FEATURE_ENABLED være på (ikke
en del av denne PR'en).

Pynter på inngangen til alder / uføre

---

src/pages/saksbehandling/sakintro/Sakintro.tsx
src/types/Regulering.ts

Har også fjernt ubrukt felt på reguleringer.

Ikke vis headerknapper for saker som ikke har noe innvilget

---

src/components/FnrInput/FnrInput.tsx
src/pages/søknad/steg/alderspensjon/alderspensjon-nb.ts
src/pages/søknad/steg/bo-og-opphold-i-norge/Bo-og-opphold-i-norge.tsx
src/pages/søknad/steg/bo-og-opphold-i-norge/EktefellePartnerSamboer.tsx
src/pages/søknad/steg/for-veileder/ForVeileder.tsx
src/pages/søknad/steg/for-veileder/forVeileder-nb.ts
src/pages/søknad/steg/oppholdstillatelse/Oppholdstillatelse.tsx
src/pages/søknad/steg/oppholdstillatelse/oppholdstillatelse-nb.ts
src/pages/søknad/steg/uførevedtak/uførevedtak-nb.ts
src/types/Søknad.ts

- fjernet inlt også
- fikset også bug ved at det krasjer når man trykker 'enter' ved fødselsnummer feltet
- fikset også at man får trykket på navnet på adressen dersom det finnes flere enn 1

oppdater tekster i søknad & fiks at spm dukker opp feil & bug fixes

---

src/pages/saksbehandling/sakintro/Sakintro.tsx

En feil i produksjon där behandlings-velgern ikke vistes for en sak med avslag.
* Klagebehandling skal kunne opprettes når det finnes ett eller flere vedtak.
* Revurdering skal kunne gjøres når det finnes minst en innvilget søknadsbehandling.

Vis behandlings-velgern når det finnes ett eller flere vedtak.

---

src/components/formElements/FormElements.tsx
src/pages/saksbehandling/revurdering/uførhet/Uførhet.tsx
src/pages/saksbehandling/steg/uføre/UføreperiodeForm.tsx
src/pages/saksbehandling/steg/uføre/UførhetForm.tsx
src/pages/saksbehandling/steg/uføre/types.ts
src/pages/saksbehandling/steg/uføre/validation.ts
src/types/Periode.ts

Konkret forslag til hvordan man kan bruke PeriodeForm i en Controller

PeriodeForm med Controller

---

.eslintrc.js
src/components/attestering/AttesteringsForm.tsx
src/components/beregningOgSimulering/beregning/Beregning.tsx
src/components/beregningOgSimulering/beregning/beregningUtils.ts
src/components/oppsummeringAvKlage/OppsummeringAvKlage.tsx
src/components/underkjenteAttesteringer/UnderkjenteAttesteringer.tsx
src/features/søknad/innsending.slice.ts
src/pages/saksbehandling/avsluttBehandling/avsluttRevurdering/AvsluttRevurdering.tsx
src/pages/saksbehandling/avsluttBehandling/lukkSøknad/LukkSøknad.tsx
src/pages/saksbehandling/regulering/ManuellRegulering.tsx
src/pages/saksbehandling/revurdering/OppsummeringPage/forhåndsvarsel/ForhåndsvarselForm.tsx
src/pages/saksbehandling/revurdering/OppsummeringPage/oppsummeringPageForms/OppsummeringPageForms.tsx
src/pages/saksbehandling/revurdering/bosituasjon/bosituasjonPage.tsx
src/pages/saksbehandling/revurdering/endringAvFradrag/EndringAvFradrag.tsx
src/pages/saksbehandling/revurdering/formue/Formue.tsx
src/pages/saksbehandling/revurdering/formue/formueUtils.ts
src/pages/saksbehandling/revurdering/opplysningsplikt/Opplysningsplikt.tsx
src/pages/saksbehandling/revurdering/revurderingIntro/RevurderingIntroForm.tsx
src/pages/saksbehandling/revurdering/uførhet/Uførhet.tsx
src/pages/saksbehandling/revurdering/utenlandsopphold/Utenlandsopphold.tsx
src/pages/saksbehandling/søknadsbehandling/formue/Formue.tsx
src/pages/saksbehandling/søknadsbehandling/uførhet/Uførhet.tsx
src/pages/saksbehandling/søknadsbehandling/virkningstidspunkt/Virkningstidspunkt.tsx
src/pages/saksbehandling/vedtak/utils.ts
src/utils/søknadsbehandlingOgRevurdering/bosituasjon/bosituasjonUtils.ts

Remove no-null-assertion

---

package-lock.json
server/package-lock.json
src/api/behandlingApi.ts
src/components/oppsummering/vilkårsOppsummering/VilkårsOppsummering.tsx
src/components/oppsummering/vilkårsOppsummering/faktablokk/faktablokker/FormueFaktablokk.tsx
src/components/revurdering/oppsummering/vedtaksinformasjon/Vedtaksinformasjon.tsx
src/features/saksoversikt/sak.slice.ts
src/pages/saksbehandling/revurdering/formue/formueUtils.ts
src/pages/saksbehandling/søknadsbehandling/formue/Formue.tsx
src/pages/saksbehandling/søknadsbehandling/formue/utils.ts
src/types/Behandling.ts
src/types/Behandlingsinformasjon.ts
src/types/grunnlagsdataOgVilkårsvurderinger/formue/Formuevilkår.ts
src/utils/behandling/behandlingUtils.ts
src/utils/søknadsbehandling/vilkår/vilkårUtils.ts

Må ses i sammenheng med: https://github.com/navikt/su-se-bakover/pull/864

Fjern formue fra behandlingsinformasjon og bytt tilhørende endepunkt

---

src/api/behandlingApi.ts
src/components/apiErrorAlert/ApiErrorAlert-nb.ts
src/components/apiErrorAlert/apiErrorCode.ts
src/components/oppsummering/vilkårsOppsummering/VilkårsOppsummering.tsx
src/components/oppsummering/vilkårsOppsummering/faktablokk/faktablokker/FamilieforeningFaktablokk.tsx
src/features/saksoversikt/sak.slice.ts
src/pages/saksbehandling/steg/familieforening/FamilieforeningForm.tsx
src/pages/saksbehandling/steg/familieforening/familieforening-nb.ts
src/pages/saksbehandling/steg/familieforening/types.ts
src/pages/saksbehandling/søknadsbehandling/familieforening/Familieforening.tsx
src/pages/saksbehandling/søknadsbehandling/familieforening/familieforening-nb.ts
src/pages/saksbehandling/søknadsbehandling/framdriftsindikator/SaksbehandlingFramdriftsindikator.tsx
src/pages/saksbehandling/søknadsbehandling/vilkår/Vilkår.tsx
src/types/Behandlingsinformasjon.ts
src/types/Vilkårsvurdering.ts
src/types/grunnlagsdataOgVilkårsvurderinger/familieforening/Familieforening.ts
src/types/grunnlagsdataOgVilkårsvurderinger/grunnlagsdataOgVilkårsvurderinger.ts
src/utils/søknadsbehandling/vilkår/vilkårUtils.ts

Steg om familieforening i søknadsbehandlingen. Må tunes inn på backend-branchen bare (når den er 100% klar)

Legg til familieforening som søknadsbehandlingssteg

---

src/components/beregningOgSimulering/beregning/Beregning.tsx
src/components/oppsummering/vilkårsOppsummering/faktablokk/faktablokker/BeregningFaktablokk.tsx
src/components/oppsummering/vilkårsOppsummering/faktablokk/faktablokker/FormueFaktablokk.tsx
src/components/oppsummering/vilkårsOppsummering/faktablokk/faktablokker/faktablokkUtils.ts
src/components/oppsummering/vilkårsOppsummering/faktablokk/faktablokker/faktablokker-nb.ts
src/components/oppsummering/vilkårsOppsummering/faktablokk/faktablokker/faktablokker.module.less
src/components/oppsummering/vilkårsOppsummering/faktablokk/faktablokker/skatt/SkattegrunnlagFaktablokk.tsx
src/components/oppsummering/vilkårsOppsummering/faktablokk/faktablokker/skatt/skattegrunnlag-nb.ts
src/pages/saksbehandling/søknadsbehandling/vilkår/Vilkår.tsx

Samlet alle komponenter kring `SkattegrunnlagFaktablokk` in i egen fil og gjør den brukbar for formue-siden og beregning-siden

Skattegrunnlag inntekt

---

src/api/behandlingApi.ts
src/components/oppsummering/vilkårsOppsummering/VilkårsOppsummering.tsx
src/components/oppsummering/vilkårsOppsummering/faktablokk/faktablokker/AlderspensjonFaktablokk.tsx
src/components/oppsummering/vilkårsOppsummering/faktablokk/faktablokker/faktablokker-nb.ts
src/features/saksoversikt/sak.slice.ts
src/pages/saksbehandling/steg/alderspensjon/AlderspensjonForm.tsx
src/pages/saksbehandling/steg/alderspensjon/alderspensjon-nb.ts
src/pages/saksbehandling/steg/alderspensjon/types.ts
src/pages/saksbehandling/søknadsbehandling/alderspensjon/Alderspensjon.tsx
src/pages/saksbehandling/søknadsbehandling/sharedI18n-nb.ts
src/types/grunnlagsdataOgVilkårsvurderinger/alder/Aldersvilkår.ts

La til de to neste spørsmålene på alderspensjon

Legg til flere spørsmål på alderspensjon

---

.github/dependabot.yml

Brace for mange dependabot-PR'er etter denne er merget

Dependabot scanner server-mappen også

---

server/auth/index.ts
server/logger.ts
server/package-lock.json
server/package.json

Legger også inn maskering på fnr i skatt-api

Bumper pino og pino-http samt redis og redis-connect for server

---

.github/workflows/branch-deploy.yml
.github/workflows/branch.yml
.github/workflows/master.yml
.github/workflows/prod-deploy.yml

Samme som er gjort for pdfgen og bakover

Bytter fra docker.pkg.github.com til ghcr.io

---

src/pages/saksbehandling/sakintro/Sakintro.tsx
src/types/Sak.ts

Egentlig litt usikker på om vi skal gidde å skjule det, eller bare la det ligger der uten at vi kan garantere for hva som skjer videre?

Skjul revurdering og klage for alder

---

src/Root.tsx
src/components/WithDocTitle.tsx
src/pages/søknad/Søknadsvelger.tsx
src/pages/søknad/søknadsvelger.module.less
src/utils/router/ContentWrapper.tsx

Hvis du ikke er inne på et tema vet vi ikke sakstype enda. Fikser headingen før valg av uføre / alder: 
Før:
Etter:

Flytter Søknadsvelger ut av SøknadOutletContext

---

src/features/saksoversikt/sak.slice.ts
src/pages/saksbehandling/søknadsbehandling/personlig-oppmøte/PersonligOppmøte.tsx

Feilen med stopp av behandling i Personlig oppmøte er i prod.

Fikser feil med stopp i PersonligOpphold og ingen lasting av revurdering i master

---

src/lib/routes.ts
src/pages/klage/avvistKlage/AvvistKlage.tsx
src/pages/klage/sendKlageTilAttestering/SendKlageTilAttestering.tsx
src/pages/saksbehandling/attestering/attesterKlage/AttesterKlage.tsx
src/pages/saksbehandling/attestering/attesterRevurdering/AttesterRevurdering.tsx
src/pages/saksbehandling/attestering/attesterSøknadsbehandling/AttesterSøknadsbehandling.tsx
src/pages/saksbehandling/avsluttBehandling/avsluttKlage/AvsluttKlage.tsx
src/pages/saksbehandling/avsluttBehandling/avsluttRevurdering/AvsluttRevurdering.tsx
src/pages/saksbehandling/avsluttBehandling/lukkSøknad/LukkSøknad.tsx
src/pages/saksbehandling/regulering/ManuellRegulering.tsx
src/pages/saksbehandling/revurdering/OppsummeringPage/RevurderingOppsummeringPage.tsx
src/pages/saksbehandling/revurdering/OppsummeringPage/forhåndsvarsel/ForhåndsvarselForm.tsx
src/pages/saksbehandling/stans/gjenoppta/gjenopptaOppsummering.tsx
src/pages/saksbehandling/stans/stansOppsummering.tsx
src/pages/saksbehandling/søknadsbehandling/sendTilAttesteringPage/SendTilAttesteringPage.tsx

Lagde en utility-funksjon som tar inn navigate for å gjennomføre dette
for sakintro, som er den som bruker alerts

Sender state i options til navigate, og ikke i første arg

---

src/pages/saksbehandling/avsluttBehandling/lukkSøknad/lukkSøknad-nb.ts
src/utils/søknadsbehandling/vilkår/vilkårUtils.ts

Refaktorerer også utledning av vilkårsvurderingsresultater slik at disse ikke er masse nøstede ternary expressions (men det ble rip på beregning :( )

Fikser riktig vilkårvurderingstatus for flyktning

---

src/components/apiErrorAlert/ApiErrorAlert-nb.ts
src/components/apiErrorAlert/apiErrorCode.ts
src/features/klage/klageActions.ts
src/features/saksoversikt/sak.slice.ts

https://github.com/navikt/su-se-bakover/pull/989

legg til manglende klage action & fjern error som ikke lenger er aktuell

---

src/api/personApi.ts
src/pages/søknad/steg/for-veileder/ForVeileder.tsx
src/pages/søknad/steg/for-veileder/forVeileder-nb.ts

https://github.com/navikt/su-se-bakover/pull/1058

Ordlyd, utlede om bruker er digital backend

---

src/Root.tsx
src/api/featureToggleApi.ts
src/api/sakApi.ts
src/components/brevPage/BrevPage-nb.ts
src/components/brevPage/BrevPage.module.less
src/components/brevPage/BrevPage.tsx
src/lib/routes.ts
src/pages/saksbehandling/sakintro/Sakintro.tsx
src/pages/saksbehandling/sakintro/sakintro-nb.ts
src/types/dokument/Dokument.ts

https://github.com/navikt/su-se-bakover/pull/1150

Mulighet for å sende fritekstbrev på saksnivå

---

src/components/vilkårOgGrunnlagForms/formue/FormueFormUtils.ts
src/pages/søknad/steg/formue/epsFormue/EktefellesFormue.tsx
src/pages/søknad/steg/formue/epsFormue/ektefellesformue-nb.ts
src/pages/søknad/steg/formue/søkersFormue/DinFormue.tsx
src/pages/søknad/steg/formue/søkersFormue/dinformue-nb.ts
src/pages/søknad/steg/oppsummering/components/FormueOppsummering.tsx

This reverts commit 7434870490f81321f257e465031bb3f1fcaa6dc5.

Revert "ekskluder depositum ved verdi på konto"

---

src/api/pdfApi.ts
src/components/brevInput/BrevInput.tsx
src/pages/saksbehandling/avsluttBehandling/lukkSøknad/LukkSøknad.tsx
src/pages/saksbehandling/avsluttBehandling/lukkSøknad/avslag/AvslåttSøknad.tsx

https://github.com/navikt/su-se-bakover/pull/1179
ny PR: https://github.com/navikt/su-se-bakover/pull/1178

brevutkast for manglende dokumentasjon

---

src/api/skattApi.ts
src/components/hentOgVisSkattegrunnlag/HentOgVisSkattegrunnlag-nb.ts
src/components/hentOgVisSkattegrunnlag/HentOgVisSkattegrunnlag.module.less
src/components/hentOgVisSkattegrunnlag/HentOgVisSkattegrunnlag.tsx
src/pages/saksbehandling/behandlingsoversikt/Behandlingsoversikt.tsx
src/pages/saksbehandling/behandlingsoversikt/behandlingsoversikt-nb.ts
src/pages/saksbehandling/behandlingsoversikt/behandlingsoversikt.module.less
src/pages/saksbehandling/søknadsbehandling/formue/Formue.tsx
src/types/skatt/Skatt.ts

https://github.com/navikt/su-se-bakover/pull/1492
https://github.com/navikt/su-pdfgen/pull/87

Frioppslag skatt

---

src/api/skattApi.ts
src/components/hentOgVisSkattegrunnlag/HentOgVisSkattegrunnlag-nb.ts
src/components/hentOgVisSkattegrunnlag/HentOgVisSkattegrunnlag.module.less
src/components/hentOgVisSkattegrunnlag/HentOgVisSkattegrunnlag.tsx
src/components/hentOgVisSkattegrunnlag/HentOgVisSkattegrunnlagUtils.ts
src/types/skatt/Skatt.ts

https://github.com/navikt/su-se-bakover/pull/1496

Frioppslag skatt med journalføring

---

src/components/inputs/textareaWithAutosave/TextareaWithAutosave.module.less
src/components/inputs/textareaWithAutosave/TextareaWithAutosave.tsx
src/pages/saksbehandling/revurdering/OppsummeringPage/sendTilAttestering/SendTilAttestering.module.less
src/pages/saksbehandling/revurdering/OppsummeringPage/sendTilAttestering/SendTilAttestering.tsx
src/pages/saksbehandling/revurdering/revurdering-nb.ts

https://github.com/navikt/su-se-bakover/pull/1643

automatisk lagring av fritekst for revurdering

---

src/api/reguleringApi.ts
src/components/oppsummering/oppsummeringAvVilkårOgGrunnlag/oppsummeringAvVilkårOgGrunnlag-nb.ts
src/components/oppsummering/oppsummeringpar/OppsummeringPar.tsx
src/pages/drift/components/regulering/G-regulering.module.less
src/pages/drift/components/regulering/G-regulering.tsx
src/pages/saksbehandling/behandlingsoversikt/regulering/reguleringsoversikt.tsx
src/pages/saksbehandling/regulering/ManuellRegulering.tsx
src/pages/saksbehandling/regulering/manuellRegulering-nb.ts
src/pages/saksbehandling/regulering/manuellRegulering.module.less
src/pages/saksbehandling/tilbakekreving/behandleTilbakekreving/vurderTilbakekreving/VurderTilbakekreving.tsx
src/types/Periode.ts
src/types/Regulering.ts
src/utils/ReguleringUtils.ts
src/utils/periode/periodeUtils.ts

- Kan sende inn supplement fra eksterne kilder
- Utvidet context til hvorfor en regulering gikk til manuell behandling
- viser info fra eksterne kilden til saksbehandler

Utvid reguleringsfunksjonalitet

---

package.json

I workflow filen kjører man typesjekk i steget før

Ikke kjør tsc to ganger ved deploy

---

package-lock.json
package.json
server/package-lock.json
server/package.json
server/proxy.ts
server/routes.ts

bah, er forskjellige routes i prod og andre steder så derfor tryner det bare ved deploy.
Må burde bruke likt oppsett på routing så man slipper slike uforutsette problemer

Bump til express 5

---

src/components/apiErrorAlert/ApiErrorAlert-nb.ts
src/components/apiErrorAlert/apiErrorCode.ts
src/pages/saksbehandling/søknadsbehandling/virkningstidspunkt/Virkningstidspunkt.tsx
src/pages/saksbehandling/søknadsbehandling/virkningstidspunkt/virkningstidspunkt-nb.ts
src/utils/SøknadsbehandlingUtils.ts

må merges med https://github.com/navikt/su-se-bakover/pull/2049

Ha saksbehandler overstyrt også for alder

---

src/components/personlinje/Personlinje.tsx
src/pages/saksbehandling/tilbakekreving/opprettTilbakekreving/OpprettTilbakekreving.tsx

* Bedre key for behandlingsoppsummering, hvis ingen blir påstartet ødelegger det lista igjen
Burde egentlig returnert med behandlingsid men det er masse jobb i backend pga ekstra rar spørring mot kravgrunnlag/tilbakekreving

Stor forbokstav sakstype + ekstra key i react liste 🤞🏻 
