navikt/su-se-framover

src/Root.tsx
src/api/apiClient.ts
src/pages/søknad/index.tsx
src/root.module.less

- Flyttet styling fra rotkomponent til egen fil
- Viser fin melding om at man ikke har tilgang dersom man ikke har tilgang; får da også lenke om å logge inn på nytt
- Fikset bug i `apiClient` som ga uendelig redirect-loop dersom den fikk 401 (fordi vi glemte å inkrementere telleren for hvor mange ganger vi hadde prøvd 😅)
- Fjernet stegindikatoren fra inngangsiden på søknad

Innlogging: håndter 403, unngå redirect-loop ved 401

---

src/features/saksoversikt/utils.tsx
src/pages/saksbehandling/steg/Framdriftsindikator.tsx

Bug: Vi visade ikke uavklart status även om status var sett till 'uavklart' på objektet.

Framdriftsindikator uavklart fix

---

src/features/behandling/behandlingUtils.ts
src/features/saksoversikt/sak.slice.ts
src/features/saksoversikt/utils.tsx
src/pages/saksbehandling/steg/Vilkår.tsx
src/pages/saksbehandling/steg/formue/Formue.tsx
src/pages/saksbehandling/vedtak/Vedtak.tsx

Nå skal den gå tillbaks till riktig url när status på behandlingen er 'avslag' av något slag.
Refaktorert litt i Vedtakssiden i tillägg.

Change routing in vedtak depending on status

---

src/pages/saksbehandling/simulering/simulering.tsx

Vi ønsker å fjerne utbetalingsbiten fra simuleringa i behandlingsøyemed. Da mister vi utbetalingsid/opprettet. Ser ut som det rydder opp UIet litt og.

Remove grunndata from simulering view

---

package-lock.json
package.json
src/pages/saksbehandling/steg/beregning/InntektFraUtland.tsx
types/country-data-list.d.ts

For å forhindre feilskriving fra saksbehandler ønsker vi at de heller skal velge valuta fra en liste. På sikt burde nok denne f.eks. ha type-ahead/søk og/eller mulighet for å velge land eller valutanavn, men vi putter den i første omgang kun inn med 3-bokstavs-valutakode: EUR, NOK, osv.

Add a dropdown to select currency for utenlandsk inntekt

---

src/features/saksoversikt/utils.tsx
src/pages/saksbehandling/steg/personlig-oppmøte/PersonligOppmøte.tsx
src/pages/saksbehandling/steg/personlig-oppmøte/personligOppmøte-nb.ts
src/types/Behandlingsinformasjon.ts

Personlig oppmøte er endret fra 4 statuser + legeerklæring, til 1 spørsmål om hvorvidt bruker har møtt personlig, og en haug med valg dersom svaret på det er nei (hvor bare ett av de fører til avslag).

Update choices for personlig oppmøte

---

src/features/behandling/behandlingUtils.ts
src/pages/saksbehandling/steg/Vurdering.tsx
src/pages/saksbehandling/steg/flyktning/Flyktning.tsx
src/pages/saksbehandling/steg/flyktning/flyktning-nb.ts
src/pages/saksbehandling/steg/sharedI18n-nb.ts

Nå skal all text och handlingar i samband med det tidiga avslaget basera sig på det som är i nuvarande tillstånd (`formik.values`) istället för i det som är lagret i backend.

Make texts dynamic based on input for tidig avslag during saksbehandling

---

src/features/saksoversikt/utils.tsx
src/pages/saksbehandling/steg/opphold-i-utlandet/OppholdIUtlandet.tsx
src/pages/saksbehandling/steg/personlig-oppmøte/PersonligOppmøte.tsx
src/pages/saksbehandling/steg/personlig-oppmøte/personligOppmøte-nb.ts
src/pages/saksbehandling/steg/personlig-oppmøte/personligOppmøte.module.less
src/styles/utils.less
src/styles/variables.less
src/types/Behandlingsinformasjon.ts

Dersom man står på personlig oppmøte og vilkårene er ikke-oppfylt vil "neste-knappen" nå vise "Gå til vedtaket", som er den oppførselen den faktisk vil ha.
Har også lagt inn en advarsel og en sperre på det steget dersom vilkårsvurderingen ikke er ferdig. Man får da en melding om at ett eller flere av vilkårene må vurderes før man kan gå videre.
Avhenger av https://github.com/navikt/su-se-bakover/pull/118.

Behandling: add status Uavklart for personlig oppmøte and utenlandsopphold

---

src/pages/saksbehandling/Saksoversikt.tsx

Fanns ett case når man sökte upp søker/søker med ektefelle som hade kode 6/7 och så visade man bara en error melding om att det var statuskode 403.
Har nå fixat så att den skal vise error-melding istedet.

Add general error handling in Saksoversikt

---

src/pages/attestering/attestering.module.less
src/pages/saksbehandling/lukkSøknad/Avvist.tsx
src/pages/saksbehandling/lukkSøknad/LukkSøknad.tsx
src/pages/saksbehandling/lukkSøknad/lukkSøknad-nb.ts
src/pages/saksbehandling/lukkSøknad/lukkSøknad.module.less
src/pages/saksbehandling/lukkSøknad/lukkSøknadUtils.ts
src/pages/saksbehandling/sakintro/sakintro.module.less
src/pages/saksbehandling/steg/vurdering.module.less
src/pages/saksbehandling/vedtak/vedtak.module.less
src/pages/søknad/index.module.less
src/pages/søknad/steg-shared.module.less
src/pages/søknad/steg/bo-og-opphold-i-norge/Bo-og-opphold-i-norge.tsx
src/pages/søknad/steg/bo-og-opphold-i-norge/EktefellePartnerSamboer.tsx
src/pages/søknad/steg/bo-og-opphold-i-norge/bo-og-opphold-i-norge.module.less
src/pages/søknad/steg/bo-og-opphold-i-norge/ektefelle-partner-samboer.module.less
src/pages/søknad/steg/ektefelle/EktefellesFormue.tsx
src/pages/søknad/steg/ektefelle/EktefellesInntekt.tsx
src/pages/søknad/steg/for-veileder/ForVeileder.tsx
src/pages/søknad/steg/formue/DinFormue.tsx
src/pages/søknad/steg/inntekt/Inntekt.tsx
src/pages/søknad/steg/kvittering/Kvittering.tsx
src/pages/søknad/steg/kvittering/kvittering.module.less
src/styles/variables.less

- Bottom margin på Lukksøknad, så den blir lik alle andre sider. 
- EPS i boforhold får validering på feltene de tilhører, istedenfor å bare vise 'ugyldig informasjon' på fødselsnummeret. 
Samtidig bevarer feilmeldinger om at de må fylles ut om EPS i seg selv er null. 
- dato for utskrivelse har en test som sjekker om feltet er fyllt inn, og gir passende feilmelding om det. 
- Datepicker har ikke feil prop av noe slag. Wrapper den i en div som gir rød ramme hvis det er feil. 
- Litt styling fix
- Lagt til manglende feil-props på inputfelter

Diverse fix

---

src/api/personApi.ts
src/components/PersonAdvarsel.tsx
src/components/Personkort.tsx
src/features/behandling/behandlingUtils.ts
src/pages/saksbehandling/steg/faktablokk/faktablokker/SatsFaktablokk.tsx
src/pages/saksbehandling/steg/formue/Formue.tsx
src/pages/saksbehandling/steg/sats/Sats.tsx
src/pages/saksbehandling/steg/sats/utils.ts
src/pages/saksbehandling/vilkårsOppsummering/VilkårsOppsummering.tsx
src/pages/søknad/steg/bo-og-opphold-i-norge/EktefellePartnerSamboer.tsx
src/types/Behandlingsinformasjon.ts

Rydder også opp en del rariteter rundt ektefelle, bl.a. at alder ble satt på i en roundtrip til backend, og fjerner et nå unødvendig `EPSMedAlder`-objekt og spesifikt personkort.

Bruk fødselsdato til å kalkulere alder

---

src/pages/saksbehandling/steg/faktablokk/faktablokker/LovligOppholdFaktablokk.tsx

False ble her tidligere maskert som om spørsmålet ikke hadde blitt besvart.

Håndter false som nei i info fra søknaden om lovlig opphold i Norge

---

src/pages/saksbehandling/steg/faktablokk/faktablokker/UtenlandsOppholdFaktablokk.tsx

Før viste vi noe ala 
```
Planlagt oppholdet i utlandet: Ingen registrerte perioder
Datoer for opphold i siste 90 dager: Ingen registrerte perioder
```
Mens nå viser vi heller ingenting dersom det ikke ble fylt inn datoer for én eller begge av periodene.

Vis opphold-i-utlandet-datoblokker kun dersom datoer ble fylt inn i søknad

---

src/pages/søknad/steg/for-veileder/ForVeileder.tsx
src/pages/søknad/steg/for-veileder/forVeileder-nb.ts

Hvis det mangler kontaktinfo i dag, så juger visningen litt og det er vanskelig for veileder å se at det mangler kontaktinfo i KRR.

Vis en melding dersom det ikke finnes informasjon i DKIF/KRR

---

src/pages/saksbehandling/steg/beregningOgSimulering/simulering/simulering.tsx

Vi klarte visst å glemme å også gruppere på beløpet.

Fiks gruppering av perioder i simulering

---

package-lock.json
package.json
src/api/behandlingApi.ts
src/components/datePicker/DatePicker.tsx
src/features/behandling/behandlingUtils.ts
src/features/saksoversikt/sak.slice.ts
src/features/saksoversikt/utils.ts
src/lib/dateUtils.ts
src/lib/fp.ts
src/lib/routes.ts
src/lib/validering.ts
src/pages/saksbehandling/steg/beregningOgSimulering/beregning/Beregning.tsx
src/pages/saksbehandling/steg/beregningOgSimulering/beregning/beregning-nb.ts
src/pages/saksbehandling/steg/framdriftsindikator/Framdriftsindikator.tsx
src/pages/saksbehandling/steg/vilkår/Vilkår.tsx
src/pages/saksbehandling/steg/virkningstidspunkt/Virkningstidspunkt.tsx
src/pages/saksbehandling/steg/virkningstidspunkt/virkningstidspunkt-nb.ts
src/pages/saksbehandling/steg/virkningstidspunkt/virkningstidspunkt.module.less
src/redux/utils.ts
src/types/Behandling.ts
src/types/Vilkårsvurdering.ts

En interessant ting her er at jeg har dratt inn `react-hook-form` for å se om det kan være et godt alternativ til `formik`.
Så langt så liker jeg det godt. Det virker å passe mye bedre til vårt bruk, og gjør en del ting enklere; f.eks. det å kunne imperativt trigge submit som kjører validering, det å automatisk sette fokus på skjemaelementer som har feil og strengere typing på felter.
Det har også støtte for andre valideringsbiblioteker enn `yup`, men for å holde eksperimentet spisset har jeg valgt å bruke `yup` her. Har sett litt på `zod` tidligere; det har mye bedre typing, men har ikke noen god løsning på validering på felter som er avhengige av hverandre. Hvis de kommer med en oppdatering som forbedrer dette bør vi vurdere å bytte ut `yup`.

Velg stønadsperiode i starten av søknadsbehandling

---

src/lib/arrayUtils.test.ts
src/lib/arrayUtils.ts
src/pages/saksbehandling/steg/beregningOgSimulering/beregning/Beregning.tsx
src/types/Beregning.ts
src/types/Fradrag.ts

Ser ut som många av våra `Eq`-functions blev deprecated i den nya oppdateringen av pakkerna.

Fiks bruk av deprecated functions fra fp-ts

---

src/features/revurdering/sharedMessages-nb.ts
src/pages/saksbehandling/revurdering/revurderingIntro/EndreRevurderingPage.tsx
src/pages/saksbehandling/revurdering/revurderingIntro/NyRevurderingPage.tsx
src/pages/saksbehandling/revurdering/revurderingIntro/RevurderingIntroForm.tsx
src/pages/saksbehandling/revurdering/revurderingskallFeilet/RevurderingskallFeilet.tsx
src/pages/saksbehandling/revurdering/revurderingskallFeilet/revurderingskallFeilet-nb.ts
src/types/Revurdering.ts

Fjerner sperrer som forhindrer opprettelse av revurderinger tilbake i tid.
Åpner for en del tilfeller som ikke støttes, må tas inn etter at nye sperringer lagt til av #324 er på plass. Se backend for denne oppgaven her: https://github.com/navikt/su-se-bakover/pull/325

Åpne for å kunne revurdere tilbake i tid.

---

server/session.ts

Gjør et forsøk på å ekskludere cookie-middleware for /api/toggles kallet

Ikke refresh cookie ved toggles kall

---

src/pages/saksbehandling/revurdering/revurderingUtils.ts

Vis checkbox for nei/ja på forhåndsvarsel frem til forhåndsvarsel er sendt. Nyttig å kunne endre mening etter revurdering er underkjent av attestant (f.eks).
Backend: https://github.com/navikt/su-se-bakover/pull/342

Gjør det mulig å endre mening fra nei til ja for forhåndsvarsel.

---

.eslintrc.js
src/components/beregningOgSimulering/BeregningOgSimulering.tsx
src/components/beregningOgSimulering/beregning/FradragInputs.tsx
src/components/beregningOgSimulering/simulering/simulering.tsx
src/components/oppsummering/BehandlingHeader.tsx
src/components/oppsummering/Behandlingsoppsummering.tsx
src/pages/saksbehandling/lukkSøknad/Avvist.tsx
src/pages/saksbehandling/lukkSøknad/LukkSøknad.tsx
src/pages/saksbehandling/revurdering/OppsummeringPage/RevurderingOppsummeringPage.tsx
src/pages/saksbehandling/revurdering/bosituasjon/BosituasjonForm.tsx
src/pages/saksbehandling/sakintro/Sakintro.tsx
src/pages/saksbehandling/steg/sats/Sats.tsx
src/pages/søknad/index.tsx

Den forstår ikke props hvis den ligger nøstet i en annen komponent, så da må den trekkes ut. Hvis det blir plagsomt, så kan vi bare fjerne regelen. Men kan være fin å skru på fra tid til annen. Eventuelt legge det som warning

fjern ubrukte props

---

src/api/revurderingApi.ts
src/features/revurdering/revurderingActions.ts
src/features/saksoversikt/sak.slice.ts
src/types/Revurdering.ts

Bakover har oppdatert retur-typen for api-kallet som gjøres når man oppdaterer grunnlag for uførhet.
PR:en tar i bruk den nya typen.

Fiks bug med oppdatering av grunnlag for uførhet

---

src/pages/saksbehandling/søknadsbehandling/fast-opphold-i-norge/FastOppholdINorge.tsx
src/pages/saksbehandling/søknadsbehandling/flyktning/Flyktning.tsx
src/pages/saksbehandling/søknadsbehandling/formue/Formue.tsx
src/pages/saksbehandling/søknadsbehandling/institusjonsopphold/Institusjonsopphold.tsx
src/pages/saksbehandling/søknadsbehandling/lovlig-opphold-i-norge/LovligOppholdINorge.tsx
src/pages/saksbehandling/søknadsbehandling/opphold-i-utlandet/OppholdIUtlandet.tsx
src/pages/saksbehandling/søknadsbehandling/personlig-oppmøte/PersonligOppmøte.tsx
src/pages/saksbehandling/søknadsbehandling/sats/Sats.tsx

Var en bug på en del av stegene våre, hvor lagre og fortsett senere aldri kalte på handleren sin.
Vi ønsker
```javascript
clickHandler={clickHandlerFunction()}
```
Ikke
```javascript
clickHandler={() => clickHandlerFunction()}
```

Fix lagre og fortsett senere

---

src/components/datePicker/DatePicker.tsx
src/components/datePicker/datePicker.module.less

Den forsvant tidligere langt utenfor input-feltet sitt.

Fiks X-knappen i datepicker

---

src/components/oppsummering/vilkårsOppsummering/faktablokk/faktablokker/faktablokker-nb.ts
src/components/oppsummering/vilkårsOppsummering/vilkårsOppsummering.module.less
src/components/søknadsbehandlingoppsummering/Søknadsbehandlingoppsummering.tsx

Fikser også sånn at overskriften "Ektefelle/samboer" brekker fint når den ikke har plass i bredden.

Fiks bakgrunn- og borderfarger i vedtaksoppsummering

---

src/components/beregningOgSimulering/beregning/Beregning.tsx

Begrunnelsen blir bare lagret når man kjører beregningen. Har endret litt på flyten, og lagt på validering som gjør at man ikke får lov til å trykke Neste uten å ha kjørt beregning dersom man har endret på begrunnelsen.

Fiks bug hvor begrunnelse ikke ble lagret på Neste

---

src/components/beregningOgSimulering/beregning/Beregning.tsx

Siden vi ikke gjør et side-skift, blir man sittende fast på siden hvis man ikke fyller ut noe data

fjern tidlig return på beregning dersom formet er likt

---

src/pages/saksbehandling/attestering/attesterSøknadsbehandling/AttesterSøknadsbehandling.tsx

Dersom den er disabled, hopper den til den nest gyldige-verdien i selecten, men denne blir ikke satt i state. 
Det kan bli forvirrende fordi i selecten ser det ut som at en verdi er valgt, men er tom i state.

fjern disabled prop til select for underkjenning

---

src/pages/saksbehandling/søknadsbehandling/formue/Formue.tsx

Nå lagres EPS, og så kaster vi saksbehandleren ut til forsiden igjen, siden de mister tilgang til saken.

Fiks håndtering av det å legge til EPS med kode 6 for en saksbehandler som ikke har tilgang

---

src/pages/saksbehandling/søknadsbehandling/formue/Formue.tsx
src/pages/saksbehandling/søknadsbehandling/formue/formue-nb.ts
src/pages/saksbehandling/søknadsbehandling/formue/utils.ts

Endre slik at vi da *kun* lagrer EPS, i stedet for å lagre hele formue-skjemaet.

Håndter lagring av EPS med kode 6 når saksbehandler ikke har nok rettigheter

---

src/components/søknadsbehandlingoppsummering/SøknadsbehandlingHeader.tsx
src/components/søknadsbehandlingoppsummering/søknadsbehandling-nb.ts
src/pages/saksbehandling/søknadsbehandling/sendTilAttesteringPage/sendTilAttesteringPage-nb.ts

Akkurat nå står det `Utkast til vedtaksbrev` selv om det er iverksatt.

Bruk forskjellig label for vedtaksbrev hvis utkast eller iverksatt

---

src/types/Revurdering.ts

Dvs. fjern "Manglende kontrollerklæring" og "Mottatt kontrollerklæring" som bare brukes ifm. stans/gjenoppta.

Fjern revurderingsårsaker man ikke skal kunne velge fra listen

---

src/api/personApi.ts
src/components/toKolonner/toKolonner.module.less
src/pages/saksbehandling/revurdering/utenlandsopphold/utenlandsopphold.module.less
src/pages/saksbehandling/søknadsbehandling/virkningstidspunkt/Virkningstidspunkt.tsx
src/pages/saksbehandling/søknadsbehandling/virkningstidspunkt/virkningstidspunkt-nb.ts
src/pages/saksbehandling/søknadsbehandling/virkningstidspunkt/virkningstidspunkt.module.less
src/pages/søknad/steg/inngang/inngang-nb.ts

Vise fødselsdato til søker (ettersom saksbehandler blir bedt om å ta stilling til denne), samt en typo-fix

Vis fødselsdato i saksbehandlersøknad

---

src/components/oppsummering/vilkårsOppsummering/VilkårsOppsummering.tsx
src/components/revurdering/oppsummering/vedtaksinformasjon/Vedtaksinformasjon.tsx

Saksbehandlerne ønsker å se hva som ble gjort på sats hvis det blir et avslag eller et opphør pga. inntekt (hvor satsen da er et ledd i beregningen).

Vis sats-info ved avslag og opphør pga. inntekt

---

src/pages/saksbehandling/søknadsbehandling/formue/Formue.tsx

Denne tilbakemelding fick vi tidligere:
epsFnr must be a `string` type, but the final value was: `null`. If "null" is intended as an empty value be sure to mark the schema as `.nullable()`

Fiks bug i yup validering for epsFnr

---

src/pages/saksbehandling/behandlingsoversikt/ferdigeBehandlinger/FerdigeBehandlinger.tsx
src/pages/saksbehandling/behandlingsoversikt/filter/Filter.tsx
src/pages/saksbehandling/restans/restanser-nb.ts
src/types/Restans.ts

Fom og Tom endres til starten/slutten av dagen (dette fikser bug hvis man velger samme dato for fom og tom, så vises ingenting, når det skal vises for den dagen)
nye statuser er: Stans, gjenopptak, og oversendt

Fjern avsluttede behandlinger & legg inn nye statuser

---

src/pages/saksbehandling/attestering/attesterRevurdering/AttesterRevurdering.tsx
src/pages/saksbehandling/revurdering/OppsummeringPage/RevurderingOppsummeringPage.tsx
src/utils/revurdering/revurderingUtils.ts

Må sjekke om revurderingen fører til opphør, da simuleringen i prod ikke gir ut ingen endringer-perioder som det gjør lokalt.
vs

Vis warning for opphør og tilbakekreving

---

package-lock.json
package.json
src/Root.tsx
src/lib/routes.ts
src/pages/klage/Klage.tsx
src/pages/saksbehandling/Saksoversikt.tsx
src/pages/saksbehandling/attestering/Attestering.tsx
src/pages/saksbehandling/behandlingsoversikt/Behandlingsoversikt.tsx
src/pages/saksbehandling/revurdering/Revurdering.tsx
src/pages/saksbehandling/sakintro/SøknadsLister.tsx
src/pages/saksbehandling/sakintro/Utbetalinger.tsx
src/pages/saksbehandling/stans/Stans.tsx
src/pages/saksbehandling/stans/gjenoppta/gjenoppta.tsx
src/pages/saksbehandling/stans/gjenoppta/gjenopptaOppsummering.tsx
src/pages/saksbehandling/stans/stansOppsummering.tsx
src/pages/saksbehandling/søknadsbehandling/sats/Sats.tsx
src/pages/saksbehandling/søknadsbehandling/vilkår/Vilkår.tsx
src/pages/søknad/index.tsx

Steg 1 for å få inn v6
Installert en migreringspakke som støtter både v5 og v6
Erstattet Route med CompatRoute der det er mulig. Nested Switch og CompatRoute ser ut til å funke litt dårlig, så har ikke fått fjernet alle Route - men nesten. Resten forsvinner i de neste migreringene.
En stor endring fra v5 til v6 er at v6 ikke tillater optional arguments i urlen:
```
- <Route path="/one/:two?" element={Comp} />
+ <CompatRoute path="/one/:two" element={Comp} />
+ <CompatRoute path="/one" element={Comp} />
```
Det kommer til å komme litt PR-er på denne migreringen (før den da er helt i boks), da det er ganske store endringer hele veien

React router 6

---

package-lock.json
server/package-lock.json
src/components/personadvarsel/PersonAdvarsel.tsx
src/components/personkort/Personkort.tsx
src/components/personkort/PersonkortHelper.tsx

Forrige forsøk med oppgradering av React Router crasha i PreProd. Jeg vet ikke hvorfor, men det at Personkort.tsx importerte fra PersonAdvarsel.tsx, PersonUtils.ts og Gender-icons gjorde at løsningen krasjet. "Kunne ikke finne modulen 'lOsyk'" var den kryptiske meldingen.
Disse endringene gjør at vi kan legge inn igjen den første migreringen til ReactRouter V6

Fix test crash ved at Peronkort.tsx ikke kunne importere fra PersonAdvarsel.tsx

---

src/Root.tsx
src/lib/routes.ts
src/pages/klage/Klage.tsx
src/pages/klage/opprettKlage/OpprettKlage.tsx
src/pages/kontrollsamtale/KontrollsamtalePage.tsx
src/pages/saksbehandling/Saksoversikt.tsx
src/pages/saksbehandling/attestering/Attestering.tsx
src/pages/saksbehandling/attestering/attesterKlage/AttesterKlage.tsx
src/pages/saksbehandling/attestering/attesterRevurdering/AttesterRevurdering.tsx
src/pages/saksbehandling/attestering/attesterSøknadsbehandling/AttesterSøknadsbehandling.tsx
src/pages/saksbehandling/avsluttBehandling/AvsluttBehandling.tsx
src/pages/saksbehandling/dokumenter/DokumenterPage.tsx
src/pages/saksbehandling/revurdering/Revurdering.tsx
src/pages/saksbehandling/revurdering/revurderingIntro/RevurderingIntroPage.tsx
src/pages/saksbehandling/sakintro/Sakintro.tsx
src/pages/saksbehandling/stans/Stans.tsx
src/pages/saksbehandling/stans/components/StansOppsummeringskomponent.tsx
src/pages/saksbehandling/stans/gjenoppta/gjenoppta.tsx
src/pages/saksbehandling/stans/gjenoppta/gjenopptaOppsummering.tsx
src/pages/saksbehandling/stans/stansOppsummering.tsx
src/pages/saksbehandling/søknadsbehandling/sendTilAttesteringPage/SendTilAttesteringPage.tsx
src/pages/saksbehandling/søknadsbehandling/vilkår/Vilkår.tsx
src/pages/saksbehandling/vedtak/Vedtaksoppsummering.tsx
src/pages/søknad/index.tsx
src/pages/søknad/steg/infoside/Infoside.tsx
src/pages/søknad/steg/inngang/Inngang.tsx
src/pages/søknad/steg/start-utfylling/StartUtfylling.tsx
src/utils/router/ContentWrapper.tsx
src/utils/router/routerUtils.ts

Dro alle Routes ut til Root. Nå har vi også et lesbart hierarki hvor vi ser hva som ligger innenfor hver subroute
En stor endring her er bruk av `<Outlet />`. Denne kan sammenlignes litt med `children` da denne rendrer det som returneres av en Route. [Her](https://reactrouter.com/docs/en/v6/api#outlet) kan man lese mer om den, evt spørre meg 🤓

Router cleanup

---

server/routes.ts

Trengte bara å sette vilken port hot reloaden skulle connecte seg mot.
Noter att når endringer gjøres i `/server` så restartes servern av nodemon og hot reloading-websocketen stenges ned, da må man refresha for å få det å funka igjen. Men skal gå fint så länge man bara fikser øvrige frontend filer.

Fikset hot reloading

---

src/pages/søknad/steg/inngang/Inngang.tsx
src/pages/søknad/steg/inntekt/TrygdeytelserInputs/TrygdeytelserInputs.tsx
src/pages/søknad/steg/inntekt/epsInntekt/EktefellesInntekt.tsx
src/pages/søknad/steg/inntekt/pensonsinntekter/Pensjonsinntekter.tsx
src/pages/søknad/steg/inntekt/søkersInntekt/Inntekt.tsx

Fjernet formik på Inntektstegene. Gjenbrukte i samme slengen Inntekt-formen for både PersonligInntekt og ektefelleInntekt

Fjern formik

---

src/pages/søknad/steg/infoside/Infoside.tsx
src/pages/søknad/steg/infoside/infoside-nb.ts
src/pages/søknad/steg/inngang/inngang-nb.ts
src/pages/søknad/utils.ts

Gjenbruker i hovedsak infosiden for SU ufør, og bytter til spesialiserte tekster der det er forskjeller. Det er også en liten endring med på dokumentasjon-siden (Inngang), som skal være for både alder og ufør.

Infoside for SU alder

---

src/api/sakApi.ts
src/components/personadvarsel/personAdvarsel.module.less
src/lib/routes.ts
src/pages/søknad/Søknadsvelger.tsx
src/pages/søknad/index.tsx
src/pages/søknad/steg/Steg.tsx
src/pages/søknad/steg/infoside/Infoside.tsx
src/pages/søknad/steg/inngang/Inngang.tsx
src/pages/søknad/steg/inngang/inngang-nb.ts
src/pages/søknad/steg/inngang/inngang.module.less
src/pages/søknad/steg/oppsummering/Oppsummering.tsx
src/pages/søknad/steg/oppsummering/Søknadoppsummering/Søknadoppsummering.tsx
src/pages/søknad/steg/oppsummering/components/EndreSvar.tsx
src/pages/søknad/steg/start-utfylling/StartUtfylling.tsx
src/pages/søknad/utils.ts
src/types/Sak.ts
src/types/Søknad.ts
src/utils/person/personUtils.ts

Siden man kan ha forskjellige kombinasjoner av søkere stil su og eksisterende
søknader om alder / uføre su så trenger man et mer detaljert nivå av meldinger.
Foreløpig er endringene i tekster ikke finalized.
Krever en endring i su-se-bakover på endepunktet for informasjon om eksisterende
søknader.

Forskjellige advarsler basert på allerede åpne søknader

---

src/pages/saksbehandling/steg/uføre/UførhetForm.tsx
src/pages/saksbehandling/søknadsbehandling/SøknadsbehandlingWrapper.tsx
src/pages/saksbehandling/søknadsbehandling/fast-opphold-i-norge/FastOppholdINorge.tsx
src/pages/saksbehandling/søknadsbehandling/flyktning/Flyktning.tsx
src/pages/saksbehandling/søknadsbehandling/formue/Formue.tsx
src/pages/saksbehandling/søknadsbehandling/institusjonsopphold/Institusjonsopphold.tsx
src/pages/saksbehandling/søknadsbehandling/lovlig-opphold-i-norge/LovligOppholdINorge.tsx
src/pages/saksbehandling/søknadsbehandling/opphold-i-utlandet/OppholdIUtlandet.tsx
src/pages/saksbehandling/søknadsbehandling/personlig-oppmøte/PersonligOppmøte.tsx

Oppdaget da jeg skrev inn Aldersstegene i søknadsbehandlingen at det er mye Boilerplate i søknadsbehandlingsstegene. En eller annen form for dette går igjen på hvert steg
```
<Feiloppsummering
tittel={formatMessage('feiloppsummering.title')}
className={styles.feiloppsummering}
feil={valideringsFeil}
hidden={valideringsFeil.length === 0}
ref={feiloppsummeringRef}
/>
{RemoteData.isFailure(savingState) && <ApiErrorAlert error={savingState.error} />}
{RemoteData.isSuccess(savingState) && harFeilmeldinger(savingState.value) && (
<UtfallSomIkkeStøttes feilmeldinger={savingState.value.feilmeldinger} />
)}
<RevurderingBunnknapper
tilbake={props.forrige}
onLagreOgFortsettSenereClick={form.handleSubmit((values: FormData) =>
onFormSubmit(values, () => navigate(props.avsluttUrl))
)} …
```

Skrive om søknadsbehandlingssteg til å bruke en generisk søknadsbehandlingswrapper

---

src/pages/søknad/steg/inngang/Inngang.tsx
src/pages/søknad/steg/inngang/inngang-nb.ts

Flytter renderingen av iverksatt innvilget stønadsperiode-feilen ett hakk utenfor, så den ikke forsvinner hvis det er eneste feilen.

Fikser slik at vi ikke skjuler feilmelding for aggressivt

---

.github/dependabot.yml

Det er en del overhead å fikse disse ~daglig, så det virker mer
hensiktsmessig å få en scan i uken og så ta de da. Vi får uansett
advarsler på security vulnerabilities løpende.

Scanner kun ukentlig for npm-oppdateringer

---

src/pages/saksbehandling/revurdering/opplysningsplikt/Opplysningsplikt.tsx
src/pages/saksbehandling/revurdering/utenlandsopphold/Utenlandsopphold.tsx

I revurdering så kunne man ikke visuelt se endringen om man valgte en ny periode for utenlandsopphold og opplysningsplikt. Fixed nu

Fikset pariode-bug i revurdering. Dato ble ikke endret

---

src/components/beregningOgSimulering/beregning/Beregning.tsx
src/pages/saksbehandling/bunnknapper/Navigasjonsknapper.tsx
src/pages/saksbehandling/revurdering/OppsummeringPage/oppsummeringPageForms/OppsummeringPageForms.tsx
src/pages/saksbehandling/revurdering/Revurdering.tsx
src/pages/saksbehandling/revurdering/bosituasjon/bosituasjonPage.tsx
src/pages/saksbehandling/revurdering/endringAvFradrag/EndringAvFradrag.tsx
src/pages/saksbehandling/revurdering/formue/Formue.tsx
src/pages/saksbehandling/revurdering/opplysningsplikt/Opplysningsplikt.tsx
src/pages/saksbehandling/revurdering/revurderingIntro/RevurderingIntroForm.tsx
src/pages/saksbehandling/revurdering/utenlandsopphold/Utenlandsopphold.tsx
src/pages/saksbehandling/steg/uføre/UførhetForm.tsx
src/pages/saksbehandling/søknadsbehandling/SøknadsbehandlingWrapper.tsx
src/pages/saksbehandling/søknadsbehandling/uførhet/Uførhet.tsx
src/types/Revurdering.ts

La inn SøknadsbehandlingsWrapper (som bytter navn i *neste* PR) på revurderingsstegene også. Fjerner en del boilerplate
Fjernet også Modalen fra Navigasjonsknappene da den ikke har noe der å gjøre

Revurdering bruker søknadsbehandlingswrapper

---

src/Root.tsx
src/features/saksoversikt/sak.slice.ts
src/lib/routes.ts
src/pages/saksbehandling/sakintro/sakintro-nb.ts
src/pages/saksbehandling/sakintro/utbetalinger-nb.ts
src/pages/saksbehandling/stans/gjenoppta/gjenoppta.tsx

Var en manglende konfigurasjon for nøstet route for gjenopptak,
fikset slik at det er tilsvarsende som for Stans. Passer også
på at vi henter inn ny revurdering når vi oppretter stans-revurdering

Fikser navigering tilbake fra Gjenoppta-oppsummering
